/**
 * The exercise library — bundled on the device, so the training feature works
 * offline and costs nothing. Each exercise carries how to do it in both
 * languages and a search term that opens a real demonstration video on
 * YouTube: the app cannot make videos, but it can send you straight to a good
 * one for free, which is the honest best.
 */

export type Muscle =
  | "chest" | "back" | "shoulders" | "legs" | "glutes" | "arms" | "core" | "fullbody" | "cardio";

export type Equipment = "barbell" | "dumbbell" | "machine" | "cable" | "bodyweight" | "kettlebell";

export type Exercise = {
  id: string;
  he: string;
  en: string;
  muscle: Muscle;
  equipment: Equipment;
  /** A compound (multi-joint) lift leads a session; accessories fill it out. */
  compound: boolean;
  howHe: string[];
  howEn: string[];
  /** What to search on YouTube for a form demo. */
  yt: string;
  /** True for a user's own manually-added move. */
  custom?: boolean;
};

const E = (
  id: string, he: string, en: string, muscle: Muscle, equipment: Equipment,
  compound: boolean, howHe: string[], howEn: string[], yt: string,
): Exercise => ({ id, he, en, muscle, equipment, compound, howHe, howEn, yt });

export const EXERCISES: Exercise[] = [
  // -- chest
  E("bench-press", "לחיצת חזה במוט", "Barbell bench press", "chest", "barbell", true,
    ["שכב על הספסל, אחיזה מעט רחבה מהכתפיים", "הורד את המוט לחזה ודחוף בשליטה כלפי מעלה"],
    ["Lie on the bench, grip a bit wider than shoulders", "Lower the bar to the chest and press up under control"],
    "barbell bench press proper form"),
  E("db-bench", "לחיצת חזה במשקולות", "Dumbbell bench press", "chest", "dumbbell", true,
    ["שכב עם משקולת בכל יד מעל החזה", "הורד לצדדים ודחוף חזרה עד יישור המרפקים"],
    ["Lie with a dumbbell in each hand over the chest", "Lower to the sides and press back to lockout"],
    "dumbbell bench press form"),
  E("incline-press", "לחיצת חזה עליון בשיפוע", "Incline dumbbell press", "chest", "dumbbell", true,
    ["ספסל בשיפוע 30 מעלות, משקולות מעל החזה העליון", "דחוף מעלה ורד בשליטה"],
    ["Bench at 30°, dumbbells over the upper chest", "Press up and lower slowly"],
    "incline dumbbell press form"),
  E("incline-barbell", "לחיצת חזה עליון במוט", "Incline barbell press", "chest", "barbell", true,
    ["ספסל בשיפוע 30 מעלות, מוט מעל החזה העליון", "הורד לחזה ודחוף מעלה בשליטה"],
    ["Bench at 30°, bar over the upper chest", "Lower to the chest and press up under control"],
    "incline barbell bench press form"),
  E("decline-press", "לחיצת חזה תחתון", "Decline press", "chest", "barbell", true,
    ["ספסל בשיפוע יורד, מוט מעל החזה התחתון", "הורד לחזה התחתון ודחוף מעלה"],
    ["Decline bench, bar over the lower chest", "Lower to the lower chest and press up"],
    "decline bench press form"),
  E("pushup", "שכיבות סמיכה", "Push-up", "chest", "bodyweight", true,
    ["ידיים מעט רחבות מהכתפיים, גוף ישר", "רד עד שהחזה כמעט נוגע, דחוף חזרה"],
    ["Hands slightly wider than shoulders, body straight", "Lower until the chest nearly touches, press back"],
    "push up proper form"),
  E("chest-fly", "פרפר חזה", "Chest fly", "chest", "dumbbell", false,
    ["שכב עם משקולות מעל החזה, מרפקים רכים", "פתח לצדדים בקשת וסגור מעל החזה"],
    ["Lie with dumbbells over the chest, soft elbows", "Open in an arc and squeeze back together"],
    "dumbbell chest fly form"),
  E("cable-crossover", "קרוסאובר בפולי", "Cable crossover", "chest", "cable", false,
    ["עמוד במרכז, כבלים גבוהים, מרפק רך", "משוך את הידיות קדימה וסגור מול החזה"],
    ["Stand centered, high cables, soft elbow", "Bring the handles forward and together at the chest"],
    "cable crossover form"),
  E("machine-chest-press", "לחיצת חזה במכונה", "Machine chest press", "chest", "machine", true,
    ["שב עם הגב צמוד, ידיות בגובה החזה", "דחוף קדימה עד יישור וחזור לאט"],
    ["Sit with the back flat, handles at chest height", "Press forward to lockout and return slowly"],
    "machine chest press form"),
  E("pec-deck", "פק דק", "Pec deck", "chest", "machine", false,
    ["שב עם הגב צמוד, מרפקים על הכריות", "סגור את הכריות מול החזה וחזור לאט"],
    ["Sit back flat, forearms on the pads", "Squeeze the pads together at the chest and return slowly"],
    "pec deck machine form"),
  // -- back
  E("deadlift", "דדליפט", "Deadlift", "back", "barbell", true,
    ["רגליים ברוחב אגן, אחוז את המוט מחוץ לברכיים", "גב ישר, דחוף דרך הרצפה והתרומם"],
    ["Feet hip-width, grip the bar outside the knees", "Flat back, drive through the floor and stand up"],
    "deadlift proper form"),
  E("pullup", "מתח", "Pull-up", "back", "bodyweight", true,
    ["אחיזה רחבה, תלייה מלאה", "משוך עד שהסנטר מעל המוט, רד בשליטה"],
    ["Wide grip, full hang", "Pull until the chin clears the bar, lower slowly"],
    "pull up proper form"),
  E("chinup", "מתח אחיזה הפוכה", "Chin-up", "back", "bodyweight", true,
    ["אחיזה צרה כף יד אליך, תלייה מלאה", "משוך עד שהסנטר מעל המוט ורד לאט"],
    ["Narrow underhand grip, full hang", "Pull until the chin clears the bar and lower slowly"],
    "chin up proper form"),
  E("bent-row", "חתירה במוט", "Barbell row", "back", "barbell", true,
    ["רכון קדימה עם גב ישר, מוט תלוי", "משוך אל הבטן התחתונה ורד בשליטה"],
    ["Hinge forward with a flat back, bar hanging", "Row to the lower belly and lower under control"],
    "barbell bent over row form"),
  E("db-row", "חתירת יד אחת במשקולת", "One-arm dumbbell row", "back", "dumbbell", true,
    ["יד וברך על הספסל, משקולת תלויה", "משוך את המשקולת אל המותן ורד לאט"],
    ["Hand and knee on the bench, dumbbell hanging", "Row the dumbbell to the hip and lower slowly"],
    "one arm dumbbell row form"),
  E("t-bar-row", "חתירת T", "T-bar row", "back", "barbell", true,
    ["רכון מעל המוט, אחוז את הידית", "משוך אל הבטן וכווץ גב, רד לאט"],
    ["Hinge over the bar, grab the handle", "Row to the belly, squeeze the back, lower slowly"],
    "t bar row form"),
  E("lat-pulldown", "משיכת פולי עליון", "Lat pulldown", "back", "cable", true,
    ["אחוז את המוט רחב, שב זקוף", "משוך אל החזה העליון וחזור לאט"],
    ["Grip the bar wide, sit tall", "Pull to the upper chest and return slowly"],
    "lat pulldown proper form"),
  E("seated-row", "חתירה בישיבה", "Seated cable row", "back", "cable", false,
    ["שב זקוף, אחוז את הידית", "משוך אל הבטן, כווץ שכמות, שחרר לאט"],
    ["Sit tall, grab the handle", "Pull to the belly, squeeze the shoulder blades, release slowly"],
    "seated cable row form"),
  E("straight-arm-pulldown", "משיכת ידיים ישרות", "Straight-arm pulldown", "back", "cable", false,
    ["עמוד מול הפולי, ידיים ישרות", "משוך את המוט אל הירכיים בקשת וחזור לאט"],
    ["Face the cable, arms straight", "Pull the bar to the thighs in an arc and return slowly"],
    "straight arm pulldown form"),
  E("shrug", "משיכת כתפיים", "Shrug", "back", "dumbbell", false,
    ["משקולות לצד הגוף, ידיים ישרות", "הרם את הכתפיים אל האוזניים וכווץ, רד לאט"],
    ["Dumbbells at the sides, arms straight", "Lift the shoulders to the ears and squeeze, lower slowly"],
    "dumbbell shrug form"),
  E("back-extension", "פשיטת גב תחתון", "Back extension", "back", "bodyweight", false,
    ["ירכיים על הכרית, גוף כפוף קדימה", "התרומם עד קו ישר עם הגוף ורד לאט"],
    ["Hips on the pad, torso folded forward", "Rise to a straight line with the body and lower slowly"],
    "back extension hyperextension form"),
  // -- shoulders
  E("ohp", "לחיצת כתפיים במוט", "Overhead press", "shoulders", "barbell", true,
    ["מוט בגובה הכתפיים, ליבה אסופה", "דחוף מעל הראש עד יישור ורד בשליטה"],
    ["Bar at shoulder height, core braced", "Press overhead to lockout and lower under control"],
    "overhead press proper form"),
  E("db-shoulder-press", "לחיצת כתפיים במשקולות", "Dumbbell shoulder press", "shoulders", "dumbbell", true,
    ["משקולות בגובה האוזניים", "דחוף מעל הראש וסגור, רד לאט"],
    ["Dumbbells at ear height", "Press overhead and together, lower slowly"],
    "dumbbell shoulder press form"),
  E("arnold-press", "לחיצת ארנולד", "Arnold press", "shoulders", "dumbbell", true,
    ["משקולות מול הפנים כף יד אליך", "סובב ודחוף מעל הראש, חזור בסיבוב"],
    ["Dumbbells in front, palms facing you", "Rotate and press overhead, reverse on the way down"],
    "arnold press form"),
  E("lateral-raise", "הרחקת כתף", "Lateral raise", "shoulders", "dumbbell", false,
    ["משקולות לצד הגוף, מרפק רך", "הרם לצדדים עד גובה הכתף ורד לאט"],
    ["Dumbbells at the sides, soft elbow", "Raise out to shoulder height and lower slowly"],
    "lateral raise proper form"),
  E("rear-delt-fly", "פרפר כתף אחורית", "Rear delt fly", "shoulders", "dumbbell", false,
    ["רכון קדימה, משקולות תלויות", "פתח לצדדים בגובה הכתף וכווץ שכמות"],
    ["Hinge forward, dumbbells hanging", "Open out to shoulder height and squeeze the shoulder blades"],
    "rear delt fly form"),
  E("front-raise", "הרמה קדמית", "Front raise", "shoulders", "dumbbell", false,
    ["משקולות מול הירכיים, מרפק רך", "הרם קדימה עד גובה הכתף ורד לאט"],
    ["Dumbbells in front of the thighs, soft elbow", "Raise forward to shoulder height and lower slowly"],
    "front raise form"),
  E("upright-row", "חתירה זקופה", "Upright row", "shoulders", "dumbbell", false,
    ["משקולות מול הירכיים, אחיזה צרה", "משוך מעלה לאורך הגוף עד החזה, רד לאט"],
    ["Dumbbells in front, narrow grip", "Pull up along the body to the chest and lower slowly"],
    "upright row form"),
  E("face-pull", "משיכת פנים", "Face pull", "shoulders", "cable", false,
    ["כבל בגובה הפנים, אחיזה בחבל", "משוך אל הפנים ופתח את המרפקים לצדדים"],
    ["Cable at face height, rope grip", "Pull to the face and flare the elbows out"],
    "face pull form"),
  // -- legs (quads, hamstrings, calves)
  E("squat", "סקוואט", "Back squat", "legs", "barbell", true,
    ["מוט על הגב העליון, רגליים ברוחב כתפיים", "רד עד שהירכיים מקבילות ודחוף מעלה"],
    ["Bar on the upper back, feet shoulder-width", "Descend to parallel and drive up"],
    "back squat proper form"),
  E("front-squat", "סקוואט קדמי", "Front squat", "legs", "barbell", true,
    ["מוט על הכתפיים הקדמיות, מרפקים גבוהים", "רד זקוף ודחוף מעלה"],
    ["Bar on the front shoulders, elbows high", "Descend upright and drive up"],
    "front squat form"),
  E("goblet-squat", "סקוואט גביע", "Goblet squat", "legs", "dumbbell", true,
    ["החזק משקולת מול החזה", "רד בין הרגליים ודחוף מעלה"],
    ["Hold a dumbbell at the chest", "Sink between the legs and drive up"],
    "goblet squat form"),
  E("hack-squat", "הק סקוואט", "Hack squat", "legs", "machine", true,
    ["גב על המשענת, רגליים על הפלטה", "רד בשליטה ודחוף מעלה בלי לנעול"],
    ["Back on the pad, feet on the platform", "Lower under control and drive up without locking"],
    "hack squat machine form"),
  E("leg-press", "לחיצת רגליים", "Leg press", "legs", "machine", true,
    ["רגליים על הפלטה ברוחב כתפיים", "רד בשליטה ודחוף בלי לנעול ברכיים"],
    ["Feet on the plate shoulder-width", "Lower under control and press without locking the knees"],
    "leg press proper form"),
  E("lunge", "מספריים", "Lunge", "legs", "dumbbell", true,
    ["צעד קדימה, רד עד שהברך האחורית כמעט נוגעת", "דחוף חזרה והחלף רגל"],
    ["Step forward, lower until the back knee nearly touches", "Push back and switch legs"],
    "dumbbell lunge form"),
  E("walking-lunge", "מספריים בהליכה", "Walking lunge", "legs", "dumbbell", true,
    ["משקולות לצד הגוף, צעד קדימה ורד", "התרומם ישר לצעד הבא ברגל השנייה"],
    ["Dumbbells at the sides, step forward and lower", "Rise straight into the next step on the other leg"],
    "walking lunge form"),
  E("bulgarian-split-squat", "סקוואט בולגרי", "Bulgarian split squat", "legs", "dumbbell", true,
    ["רגל אחורית על ספסל, משקולות בידיים", "רד עם הרגל הקדמית ודחוף מעלה"],
    ["Rear foot on a bench, dumbbells in hand", "Lower on the front leg and drive up"],
    "bulgarian split squat form"),
  E("step-up", "עלייה על ספסל", "Step-up", "legs", "dumbbell", true,
    ["עמוד מול ספסל, משקולות בידיים", "עלה עם רגל אחת, כווץ ורד בשליטה"],
    ["Stand facing a bench, dumbbells in hand", "Step up with one leg, squeeze and lower under control"],
    "dumbbell step up form"),
  E("leg-extension", "פשיטת ברך", "Leg extension", "legs", "machine", false,
    ["שב במכונה, קרסוליים מאחורי הכרית", "יישר את הברכיים וכווץ, רד לאט"],
    ["Sit in the machine, ankles behind the pad", "Straighten the knees and squeeze, lower slowly"],
    "leg extension machine form"),
  E("leg-curl", "כפיפת ברך", "Leg curl", "legs", "machine", false,
    ["שכב/שב במכונה, קרסוליים על הכרית", "כופף את הברכיים וחזור לאט"],
    ["Lie or sit in the machine, ankles on the pad", "Curl the knees and return slowly"],
    "leg curl machine form"),
  E("calf-raise", "הרמת עקבים", "Standing calf raise", "legs", "bodyweight", false,
    ["עמוד על קצות האצבעות", "הרם עקבים גבוה ורד לאט"],
    ["Stand on the balls of the feet", "Raise the heels high and lower slowly"],
    "standing calf raise form"),
  E("seated-calf-raise", "הרמת עקבים בישיבה", "Seated calf raise", "legs", "machine", false,
    ["שב עם הכרית על הברכיים, קצות אצבעות על הפלטה", "הרם עקבים גבוה ורד לאט"],
    ["Sit with the pad on the knees, toes on the platform", "Raise the heels high and lower slowly"],
    "seated calf raise form"),
  // -- glutes / posterior chain
  E("rdl", "רומני דדליפט", "Romanian deadlift", "glutes", "barbell", true,
    ["מוט מול הירכיים, ברכיים רכות", "דחוף אגן אחורה, רד לאורך הרגליים וחזור"],
    ["Bar at the thighs, soft knees", "Push the hips back, slide down the legs and return"],
    "romanian deadlift form"),
  E("hip-thrust", "הרמת אגן", "Hip thrust", "glutes", "barbell", true,
    ["גב עליון על ספסל, מוט על האגן", "דחוף את האגן מעלה וכווץ ישבן"],
    ["Upper back on a bench, bar over the hips", "Drive the hips up and squeeze the glutes"],
    "hip thrust form"),
  E("glute-bridge", "גשר ישבן", "Glute bridge", "glutes", "bodyweight", false,
    ["שכב על הגב, ברכיים כפופות, כפות רגליים על הרצפה", "דחוף אגן מעלה וכווץ ישבן, רד לאט"],
    ["Lie on your back, knees bent, feet on the floor", "Drive the hips up and squeeze the glutes, lower slowly"],
    "glute bridge form"),
  E("cable-kickback", "בעיטת ישבן בפולי", "Cable glute kickback", "glutes", "cable", false,
    ["רצועה על הקרסול, רכון קלות קדימה", "בעט את הרגל אחורה וכווץ ישבן, חזור לאט"],
    ["Strap on the ankle, lean slightly forward", "Kick the leg back and squeeze the glute, return slowly"],
    "cable glute kickback form"),
  // -- arms (biceps, triceps)
  E("biceps-curl", "כפיפת מרפק", "Biceps curl", "arms", "dumbbell", false,
    ["משקולות לצד הגוף, מרפקים צמודים", "כופף מעלה וכווץ, רד לאט"],
    ["Dumbbells at the sides, elbows pinned", "Curl up and squeeze, lower slowly"],
    "dumbbell biceps curl form"),
  E("hammer-curl", "כפיפת פטיש", "Hammer curl", "arms", "dumbbell", false,
    ["אחיזה ניטרלית, מרפקים צמודים", "כופף מעלה ורד בשליטה"],
    ["Neutral grip, elbows pinned", "Curl up and lower under control"],
    "hammer curl form"),
  E("barbell-curl", "כפיפת מרפק במוט", "Barbell curl", "arms", "barbell", false,
    ["מוט באחיזה תחתונה, מרפקים צמודים", "כופף מעלה וכווץ, רד לאט"],
    ["Bar in an underhand grip, elbows pinned", "Curl up and squeeze, lower slowly"],
    "barbell curl form"),
  E("preacher-curl", "כפיפת מרפק בכיסא כומר", "Preacher curl", "arms", "dumbbell", false,
    ["זרוע על משענת הכיסא, אחיזה תחתונה", "כופף מעלה וכווץ, רד לאט ומלא"],
    ["Arm on the preacher pad, underhand grip", "Curl up and squeeze, lower slow and full"],
    "preacher curl form"),
  E("concentration-curl", "כפיפת ריכוז", "Concentration curl", "arms", "dumbbell", false,
    ["שב, מרפק על פנים הירך", "כופף מעלה וכווץ, רד לאט"],
    ["Sit, elbow against the inner thigh", "Curl up and squeeze, lower slowly"],
    "concentration curl form"),
  E("cable-curl", "כפיפת מרפק בפולי", "Cable curl", "arms", "cable", false,
    ["עמוד מול פולי תחתון, מרפקים צמודים", "כופף מעלה וכווץ, רד לאט"],
    ["Face a low cable, elbows pinned", "Curl up and squeeze, lower slowly"],
    "cable biceps curl form"),
  E("triceps-pushdown", "פשיטת מרפק בפולי", "Triceps pushdown", "arms", "cable", false,
    ["אחוז את החבל, מרפקים צמודים", "דחוף מטה עד יישור וחזור לאט"],
    ["Grab the rope, elbows pinned", "Push down to lockout and return slowly"],
    "triceps pushdown form"),
  E("skullcrusher", "פשיטת מרפק בשכיבה", "Skullcrusher", "arms", "barbell", false,
    ["שכב, מוט מעל המצח, מרפקים למעלה", "הורד אל המצח ופשוט מעלה"],
    ["Lie down, bar over the forehead, elbows up", "Lower to the forehead and extend up"],
    "skullcrusher lying triceps extension form"),
  E("overhead-triceps", "פשיטת מרפק מעל הראש", "Overhead triceps extension", "arms", "dumbbell", false,
    ["משקולת מעל הראש בשתי ידיים", "הורד מאחורי הראש ופשוט מעלה"],
    ["Dumbbell overhead in both hands", "Lower behind the head and extend up"],
    "overhead dumbbell triceps extension form"),
  E("close-grip-bench", "לחיצת חזה אחיזה צרה", "Close-grip bench press", "arms", "barbell", true,
    ["שכב, אחיזה ברוחב כתפיים", "הורד לחזה, מרפקים צמודים, ודחוף מעלה"],
    ["Lie down, shoulder-width grip", "Lower to the chest, elbows tucked, and press up"],
    "close grip bench press form"),
  E("dips", "מקבילים", "Dips", "arms", "bodyweight", true,
    ["תלייה על מקבילים, גוף זקוף", "רד עד 90 מעלות ודחוף מעלה"],
    ["Support on parallel bars, torso upright", "Lower to 90° and press up"],
    "triceps dips form"),
  // -- core
  E("plank", "פלאנק", "Plank", "core", "bodyweight", false,
    ["מרפקים מתחת לכתפיים, גוף ישר", "אסוף ליבה והחזק"],
    ["Elbows under the shoulders, body straight", "Brace the core and hold"],
    "plank proper form"),
  E("side-plank", "פלאנק צדי", "Side plank", "core", "bodyweight", false,
    ["על הצד, מרפק מתחת לכתף, גוף ישר", "הרם אגן והחזק, החלף צד"],
    ["On your side, elbow under the shoulder, body straight", "Lift the hips and hold, switch sides"],
    "side plank form"),
  E("hanging-leg-raise", "הרמת רגליים בתלייה", "Hanging leg raise", "core", "bodyweight", false,
    ["תלייה על מוט", "הרם רגליים ישרות ורד לאט"],
    ["Hang from a bar", "Raise straight legs and lower slowly"],
    "hanging leg raise form"),
  E("crunch", "כפיפות בטן", "Crunch", "core", "bodyweight", false,
    ["שכב, ברכיים כפופות", "כווץ בטן והרם כתפיים, רד לאט"],
    ["Lie down, knees bent", "Crunch and lift the shoulders, lower slowly"],
    "crunch proper form"),
  E("bicycle-crunch", "כפיפות אופניים", "Bicycle crunch", "core", "bodyweight", false,
    ["שכב, ידיים ליד הראש", "הבא מרפק אל הברך הנגדית לסירוגין"],
    ["Lie down, hands by the head", "Bring elbow to the opposite knee, alternating"],
    "bicycle crunch form"),
  E("russian-twist", "סיבובים רוסיים", "Russian twist", "core", "bodyweight", false,
    ["שב עם ברכיים כפופות, גב מוטה אחורה", "סובב את הגו מצד לצד"],
    ["Sit with knees bent, torso leaned back", "Rotate the torso side to side"],
    "russian twist form"),
  E("mountain-climber", "טיפוס הרים", "Mountain climber", "core", "bodyweight", true,
    ["מנח שכיבת סמיכה, ליבה אסופה", "הבא ברכיים אל החזה לסירוגין במהירות"],
    ["Push-up position, core braced", "Drive the knees to the chest, alternating quickly"],
    "mountain climber form"),
  E("dead-bug", "חיפושית מתה", "Dead bug", "core", "bodyweight", false,
    ["שכב, ידיים ורגליים מורמות", "הורד יד ורגל נגדית ואסוף חזרה"],
    ["Lie down, arms and legs raised", "Lower opposite arm and leg, then return"],
    "dead bug exercise form"),
  E("cable-crunch", "כפיפת בטן בפולי", "Cable crunch", "core", "cable", false,
    ["כרע מול פולי עליון, חבל ליד הראש", "כווץ בטן וכופף מטה, חזור לאט"],
    ["Kneel at a high cable, rope by the head", "Crunch down with the abs, return slowly"],
    "cable crunch form"),
  E("ab-wheel", "גלגל בטן", "Ab wheel rollout", "core", "bodyweight", false,
    ["כרע עם הגלגל בידיים", "גלגל קדימה בגוף ישר וחזור"],
    ["Kneel holding the wheel", "Roll forward with a straight body and return"],
    "ab wheel rollout form"),
  // -- full body / cardio
  E("burpee", "ברפי", "Burpee", "fullbody", "bodyweight", true,
    ["שכיבת סמיכה, קפיצה לרגליים", "קפוץ מעלה עם ידיים גבוה"],
    ["Drop to a push-up, jump the feet in", "Jump up with the arms overhead"],
    "burpee proper form"),
  E("kb-swing", "נדנוד קטלבל", "Kettlebell swing", "fullbody", "kettlebell", true,
    ["קטלבל בין הרגליים, דחוף אגן אחורה", "נדנד מעלה בכוח האגן עד גובה החזה"],
    ["Kettlebell between the legs, hips back", "Swing up with the hips to chest height"],
    "kettlebell swing form"),
  E("thruster", "ת'ראסטר", "Thruster", "fullbody", "dumbbell", true,
    ["משקולות בגובה הכתפיים, רד לסקוואט", "התרומם ודחוף את המשקולות מעל הראש"],
    ["Dumbbells at the shoulders, drop to a squat", "Rise and press the dumbbells overhead"],
    "dumbbell thruster form"),
  E("clean-and-press", "הנפה ולחיצה", "Clean and press", "fullbody", "dumbbell", true,
    ["משקולות ליד הרצפה, הנף אל הכתפיים", "דחוף מעל הראש והורד בשליטה"],
    ["Dumbbells near the floor, pull to the shoulders", "Press overhead and lower under control"],
    "dumbbell clean and press form"),
  E("jump-rope", "קפיצה בחבל", "Jump rope", "cardio", "bodyweight", false,
    ["חבל מאחורי הגוף, מרפקים צמודים", "סובב מהשורש כף היד וקפוץ קל"],
    ["Rope behind the body, elbows tucked", "Turn from the wrists and hop lightly"],
    "jump rope for beginners form"),
  E("rowing-machine", "חתירה במכונת אירובי", "Rowing machine", "cardio", "machine", true,
    ["אחוז את הידית, רגליים כפופות", "דחוף ברגליים, משוך אל הבטן, חזור בסדר הפוך"],
    ["Grab the handle, legs bent", "Drive with the legs, pull to the belly, reverse the order"],
    "rowing machine proper form"),
  E("incline-walk", "הליכה בשיפוע", "Incline treadmill walk", "cardio", "machine", false,
    ["הצב שיפוע 8–12%, קצב נוח", "הלך זקוף בלי להיאחז במעקה"],
    ["Set incline 8–12%, easy pace", "Walk tall without holding the rail"],
    "incline treadmill walk fat loss"),
  // -- bodyweight moves, so a home or no-equipment plan is still full
  E("air-squat", "סקוואט משקל גוף", "Bodyweight squat", "legs", "bodyweight", true,
    ["רגליים ברוחב כתפיים, ידיים קדימה", "רד עד שהירכיים מקבילות ודחוף מעלה"],
    ["Feet shoulder-width, arms forward", "Sink to parallel and drive up"],
    "bodyweight squat form"),
  E("bw-lunge", "מספריים משקל גוף", "Bodyweight lunge", "legs", "bodyweight", true,
    ["צעד קדימה, רד עד שהברך האחורית כמעט נוגעת", "דחוף חזרה והחלף רגל"],
    ["Step forward, lower until the back knee nearly touches", "Push back and switch legs"],
    "bodyweight lunge form"),
  E("jump-squat", "סקוואט קפיצה", "Jump squat", "legs", "bodyweight", true,
    ["רד לסקוואט", "התפוצץ מעלה בקפיצה ונחת רך"],
    ["Drop into a squat", "Explode up into a jump and land softly"],
    "jump squat form"),
  E("wall-sit", "ישיבת קיר", "Wall sit", "legs", "bodyweight", false,
    ["גב לקיר, ירכיים במקביל לרצפה", "החזק את המנח"],
    ["Back on the wall, thighs parallel to the floor", "Hold the position"],
    "wall sit form"),
  E("pike-pushup", "שכיבת פייק", "Pike push-up", "shoulders", "bodyweight", true,
    ["מנח V הפוך, ירכיים גבוה", "רד עם הראש לרצפה ודחוף מעלה"],
    ["Inverted-V position, hips high", "Lower the head toward the floor and press up"],
    "pike push up form"),
  E("superman", "סופרמן", "Superman", "back", "bodyweight", false,
    ["שכב על הבטן, ידיים קדימה", "הרם ידיים, חזה ורגליים וכווץ גב תחתון"],
    ["Lie face down, arms forward", "Lift the arms, chest and legs and squeeze the lower back"],
    "superman exercise form"),
];

/** Everyday muscle groups that a plan cycles through. */
export const MUSCLES: Muscle[] = [
  "chest", "back", "shoulders", "legs", "glutes", "arms", "core", "fullbody",
];

// Opening a demo lives in ./video: what the app opens is the exact clip when
// it can be resolved, and only then the search page — see that file.
