/**
 * The exercise library — bundled on the device, so the training feature works
 * offline and costs nothing. Each exercise carries how to do it in both
 * languages and a search term that opens a real demonstration video on
 * YouTube: the app cannot make videos, but it can send you straight to a good
 * one for free, which is the honest best.
 */

export type Muscle =
  | "chest" | "back" | "shoulders" | "legs" | "glutes" | "arms" | "forearms"
  | "core" | "fullbody" | "cardio";

export type Equipment =
  | "barbell" | "dumbbell" | "machine" | "cable" | "bodyweight" | "kettlebell"
  | "smith" | "band";

export type Exercise = {
  id: string;
  he: string;
  en: string;
  muscle: Muscle;
  equipment: Equipment;
  /** A compound (multi-joint) lift leads a session; accessories fill it out. */
  compound: boolean;
  howHe: string[];
  howEn: string[];
  /** What to search on YouTube for a form demo. */
  yt: string;
  /** True for a user's own manually-added move. */
  custom?: boolean;
};

const E = (
  id: string, he: string, en: string, muscle: Muscle, equipment: Equipment,
  compound: boolean, howHe: string[], howEn: string[], yt: string,
): Exercise => ({ id, he, en, muscle, equipment, compound, howHe, howEn, yt });

export const EXERCISES: Exercise[] = [
  // -- chest
  E("bench-press", "לחיצת חזה במוט", "Barbell bench press", "chest", "barbell", true,
    ["שכב על הספסל, אחיזה מעט רחבה מהכתפיים", "הורד את המוט לחזה ודחוף בשליטה כלפי מעלה"],
    ["Lie on the bench, grip a bit wider than shoulders", "Lower the bar to the chest and press up under control"],
    "barbell bench press proper form"),
  E("db-bench", "לחיצת חזה במשקולות", "Dumbbell bench press", "chest", "dumbbell", true,
    ["שכב עם משקולת בכל יד מעל החזה", "הורד לצדדים ודחוף חזרה עד יישור המרפקים"],
    ["Lie with a dumbbell in each hand over the chest", "Lower to the sides and press back to lockout"],
    "dumbbell bench press form"),
  E("incline-press", "לחיצת חזה עליון בשיפוע", "Incline dumbbell press", "chest", "dumbbell", true,
    ["ספסל בשיפוע 30 מעלות, משקולות מעל החזה העליון", "דחוף מעלה ורד בשליטה"],
    ["Bench at 30°, dumbbells over the upper chest", "Press up and lower slowly"],
    "incline dumbbell press form"),
  E("incline-barbell", "לחיצת חזה עליון במוט", "Incline barbell press", "chest", "barbell", true,
    ["ספסל בשיפוע 30 מעלות, מוט מעל החזה העליון", "הורד לחזה ודחוף מעלה בשליטה"],
    ["Bench at 30°, bar over the upper chest", "Lower to the chest and press up under control"],
    "incline barbell bench press form"),
  E("decline-press", "לחיצת חזה תחתון", "Decline press", "chest", "barbell", true,
    ["ספסל בשיפוע יורד, מוט מעל החזה התחתון", "הורד לחזה התחתון ודחוף מעלה"],
    ["Decline bench, bar over the lower chest", "Lower to the lower chest and press up"],
    "decline bench press form"),
  E("pushup", "שכיבות סמיכה", "Push-up", "chest", "bodyweight", true,
    ["ידיים מעט רחבות מהכתפיים, גוף ישר", "רד עד שהחזה כמעט נוגע, דחוף חזרה"],
    ["Hands slightly wider than shoulders, body straight", "Lower until the chest nearly touches, press back"],
    "push up proper form"),
  E("chest-fly", "פרפר חזה", "Chest fly", "chest", "dumbbell", false,
    ["שכב עם משקולות מעל החזה, מרפקים רכים", "פתח לצדדים בקשת וסגור מעל החזה"],
    ["Lie with dumbbells over the chest, soft elbows", "Open in an arc and squeeze back together"],
    "dumbbell chest fly form"),
  E("cable-crossover", "קרוסאובר בפולי", "Cable crossover", "chest", "cable", false,
    ["עמוד במרכז, כבלים גבוהים, מרפק רך", "משוך את הידיות קדימה וסגור מול החזה"],
    ["Stand centered, high cables, soft elbow", "Bring the handles forward and together at the chest"],
    "cable crossover form"),
  E("machine-chest-press", "לחיצת חזה במכונה", "Machine chest press", "chest", "machine", true,
    ["שב עם הגב צמוד, ידיות בגובה החזה", "דחוף קדימה עד יישור וחזור לאט"],
    ["Sit with the back flat, handles at chest height", "Press forward to lockout and return slowly"],
    "machine chest press form"),
  E("pec-deck", "פק דק", "Pec deck", "chest", "machine", false,
    ["שב עם הגב צמוד, מרפקים על הכריות", "סגור את הכריות מול החזה וחזור לאט"],
    ["Sit back flat, forearms on the pads", "Squeeze the pads together at the chest and return slowly"],
    "pec deck machine form"),
  // -- back
  E("deadlift", "דדליפט", "Deadlift", "back", "barbell", true,
    ["רגליים ברוחב אגן, אחוז את המוט מחוץ לברכיים", "גב ישר, דחוף דרך הרצפה והתרומם"],
    ["Feet hip-width, grip the bar outside the knees", "Flat back, drive through the floor and stand up"],
    "deadlift proper form"),
  E("pullup", "מתח", "Pull-up", "back", "bodyweight", true,
    ["אחיזה רחבה, תלייה מלאה", "משוך עד שהסנטר מעל המוט, רד בשליטה"],
    ["Wide grip, full hang", "Pull until the chin clears the bar, lower slowly"],
    "pull up proper form"),
  E("chinup", "מתח אחיזה הפוכה", "Chin-up", "back", "bodyweight", true,
    ["אחיזה צרה כף יד אליך, תלייה מלאה", "משוך עד שהסנטר מעל המוט ורד לאט"],
    ["Narrow underhand grip, full hang", "Pull until the chin clears the bar and lower slowly"],
    "chin up proper form"),
  E("bent-row", "חתירה במוט", "Barbell row", "back", "barbell", true,
    ["רכון קדימה עם גב ישר, מוט תלוי", "משוך אל הבטן התחתונה ורד בשליטה"],
    ["Hinge forward with a flat back, bar hanging", "Row to the lower belly and lower under control"],
    "barbell bent over row form"),
  E("db-row", "חתירת יד אחת במשקולת", "One-arm dumbbell row", "back", "dumbbell", true,
    ["יד וברך על הספסל, משקולת תלויה", "משוך את המשקולת אל המותן ורד לאט"],
    ["Hand and knee on the bench, dumbbell hanging", "Row the dumbbell to the hip and lower slowly"],
    "one arm dumbbell row form"),
  E("t-bar-row", "חתירת T", "T-bar row", "back", "barbell", true,
    ["רכון מעל המוט, אחוז את הידית", "משוך אל הבטן וכווץ גב, רד לאט"],
    ["Hinge over the bar, grab the handle", "Row to the belly, squeeze the back, lower slowly"],
    "t bar row form"),
  E("lat-pulldown", "משיכת פולי עליון", "Lat pulldown", "back", "cable", true,
    ["אחוז את המוט רחב, שב זקוף", "משוך אל החזה העליון וחזור לאט"],
    ["Grip the bar wide, sit tall", "Pull to the upper chest and return slowly"],
    "lat pulldown proper form"),
  E("seated-row", "חתירה בישיבה", "Seated cable row", "back", "cable", false,
    ["שב זקוף, אחוז את הידית", "משוך אל הבטן, כווץ שכמות, שחרר לאט"],
    ["Sit tall, grab the handle", "Pull to the belly, squeeze the shoulder blades, release slowly"],
    "seated cable row form"),
  E("straight-arm-pulldown", "משיכת ידיים ישרות", "Straight-arm pulldown", "back", "cable", false,
    ["עמוד מול הפולי, ידיים ישרות", "משוך את המוט אל הירכיים בקשת וחזור לאט"],
    ["Face the cable, arms straight", "Pull the bar to the thighs in an arc and return slowly"],
    "straight arm pulldown form"),
  E("shrug", "משיכת כתפיים", "Shrug", "back", "dumbbell", false,
    ["משקולות לצד הגוף, ידיים ישרות", "הרם את הכתפיים אל האוזניים וכווץ, רד לאט"],
    ["Dumbbells at the sides, arms straight", "Lift the shoulders to the ears and squeeze, lower slowly"],
    "dumbbell shrug form"),
  E("back-extension", "פשיטת גב תחתון", "Back extension", "back", "bodyweight", false,
    ["ירכיים על הכרית, גוף כפוף קדימה", "התרומם עד קו ישר עם הגוף ורד לאט"],
    ["Hips on the pad, torso folded forward", "Rise to a straight line with the body and lower slowly"],
    "back extension hyperextension form"),
  // -- shoulders
  E("ohp", "לחיצת כתפיים במוט", "Overhead press", "shoulders", "barbell", true,
    ["מוט בגובה הכתפיים, ליבה אסופה", "דחוף מעל הראש עד יישור ורד בשליטה"],
    ["Bar at shoulder height, core braced", "Press overhead to lockout and lower under control"],
    "overhead press proper form"),
  E("db-shoulder-press", "לחיצת כתפיים במשקולות", "Dumbbell shoulder press", "shoulders", "dumbbell", true,
    ["משקולות בגובה האוזניים", "דחוף מעל הראש וסגור, רד לאט"],
    ["Dumbbells at ear height", "Press overhead and together, lower slowly"],
    "dumbbell shoulder press form"),
  E("arnold-press", "לחיצת ארנולד", "Arnold press", "shoulders", "dumbbell", true,
    ["משקולות מול הפנים כף יד אליך", "סובב ודחוף מעל הראש, חזור בסיבוב"],
    ["Dumbbells in front, palms facing you", "Rotate and press overhead, reverse on the way down"],
    "arnold press form"),
  E("lateral-raise", "הרחקת כתף", "Lateral raise", "shoulders", "dumbbell", false,
    ["משקולות לצד הגוף, מרפק רך", "הרם לצדדים עד גובה הכתף ורד לאט"],
    ["Dumbbells at the sides, soft elbow", "Raise out to shoulder height and lower slowly"],
    "lateral raise proper form"),
  E("rear-delt-fly", "פרפר כתף אחורית", "Rear delt fly", "shoulders", "dumbbell", false,
    ["רכון קדימה, משקולות תלויות", "פתח לצדדים בגובה הכתף וכווץ שכמות"],
    ["Hinge forward, dumbbells hanging", "Open out to shoulder height and squeeze the shoulder blades"],
    "rear delt fly form"),
  E("front-raise", "הרמה קדמית", "Front raise", "shoulders", "dumbbell", false,
    ["משקולות מול הירכיים, מרפק רך", "הרם קדימה עד גובה הכתף ורד לאט"],
    ["Dumbbells in front of the thighs, soft elbow", "Raise forward to shoulder height and lower slowly"],
    "front raise form"),
  E("upright-row", "חתירה זקופה", "Upright row", "shoulders", "dumbbell", false,
    ["משקולות מול הירכיים, אחיזה צרה", "משוך מעלה לאורך הגוף עד החזה, רד לאט"],
    ["Dumbbells in front, narrow grip", "Pull up along the body to the chest and lower slowly"],
    "upright row form"),
  E("face-pull", "משיכת פנים", "Face pull", "shoulders", "cable", false,
    ["כבל בגובה הפנים, אחיזה בחבל", "משוך אל הפנים ופתח את המרפקים לצדדים"],
    ["Cable at face height, rope grip", "Pull to the face and flare the elbows out"],
    "face pull form"),
  // -- legs (quads, hamstrings, calves)
  E("squat", "סקוואט", "Back squat", "legs", "barbell", true,
    ["מוט על הגב העליון, רגליים ברוחב כתפיים", "רד עד שהירכיים מקבילות ודחוף מעלה"],
    ["Bar on the upper back, feet shoulder-width", "Descend to parallel and drive up"],
    "back squat proper form"),
  E("front-squat", "סקוואט קדמי", "Front squat", "legs", "barbell", true,
    ["מוט על הכתפיים הקדמיות, מרפקים גבוהים", "רד זקוף ודחוף מעלה"],
    ["Bar on the front shoulders, elbows high", "Descend upright and drive up"],
    "front squat form"),
  E("goblet-squat", "סקוואט גביע", "Goblet squat", "legs", "dumbbell", true,
    ["החזק משקולת מול החזה", "רד בין הרגליים ודחוף מעלה"],
    ["Hold a dumbbell at the chest", "Sink between the legs and drive up"],
    "goblet squat form"),
  E("hack-squat", "הק סקוואט", "Hack squat", "legs", "machine", true,
    ["גב על המשענת, רגליים על הפלטה", "רד בשליטה ודחוף מעלה בלי לנעול"],
    ["Back on the pad, feet on the platform", "Lower under control and drive up without locking"],
    "hack squat machine form"),
  E("leg-press", "לחיצת רגליים", "Leg press", "legs", "machine", true,
    ["רגליים על הפלטה ברוחב כתפיים", "רד בשליטה ודחוף בלי לנעול ברכיים"],
    ["Feet on the plate shoulder-width", "Lower under control and press without locking the knees"],
    "leg press proper form"),
  E("lunge", "מספריים", "Lunge", "legs", "dumbbell", true,
    ["צעד קדימה, רד עד שהברך האחורית כמעט נוגעת", "דחוף חזרה והחלף רגל"],
    ["Step forward, lower until the back knee nearly touches", "Push back and switch legs"],
    "dumbbell lunge form"),
  E("walking-lunge", "מספריים בהליכה", "Walking lunge", "legs", "dumbbell", true,
    ["משקולות לצד הגוף, צעד קדימה ורד", "התרומם ישר לצעד הבא ברגל השנייה"],
    ["Dumbbells at the sides, step forward and lower", "Rise straight into the next step on the other leg"],
    "walking lunge form"),
  E("bulgarian-split-squat", "סקוואט בולגרי", "Bulgarian split squat", "legs", "dumbbell", true,
    ["רגל אחורית על ספסל, משקולות בידיים", "רד עם הרגל הקדמית ודחוף מעלה"],
    ["Rear foot on a bench, dumbbells in hand", "Lower on the front leg and drive up"],
    "bulgarian split squat form"),
  E("step-up", "עלייה על ספסל", "Step-up", "legs", "dumbbell", true,
    ["עמוד מול ספסל, משקולות בידיים", "עלה עם רגל אחת, כווץ ורד בשליטה"],
    ["Stand facing a bench, dumbbells in hand", "Step up with one leg, squeeze and lower under control"],
    "dumbbell step up form"),
  E("leg-extension", "פשיטת ברך", "Leg extension", "legs", "machine", false,
    ["שב במכונה, קרסוליים מאחורי הכרית", "יישר את הברכיים וכווץ, רד לאט"],
    ["Sit in the machine, ankles behind the pad", "Straighten the knees and squeeze, lower slowly"],
    "leg extension machine form"),
  E("leg-curl", "כפיפת ברך", "Leg curl", "legs", "machine", false,
    ["שכב/שב במכונה, קרסוליים על הכרית", "כופף את הברכיים וחזור לאט"],
    ["Lie or sit in the machine, ankles on the pad", "Curl the knees and return slowly"],
    "leg curl machine form"),
  E("calf-raise", "הרמת עקבים", "Standing calf raise", "legs", "bodyweight", false,
    ["עמוד על קצות האצבעות", "הרם עקבים גבוה ורד לאט"],
    ["Stand on the balls of the feet", "Raise the heels high and lower slowly"],
    "standing calf raise form"),
  E("seated-calf-raise", "הרמת עקבים בישיבה", "Seated calf raise", "legs", "machine", false,
    ["שב עם הכרית על הברכיים, קצות אצבעות על הפלטה", "הרם עקבים גבוה ורד לאט"],
    ["Sit with the pad on the knees, toes on the platform", "Raise the heels high and lower slowly"],
    "seated calf raise form"),
  // -- glutes / posterior chain
  E("rdl", "רומני דדליפט", "Romanian deadlift", "glutes", "barbell", true,
    ["מוט מול הירכיים, ברכיים רכות", "דחוף אגן אחורה, רד לאורך הרגליים וחזור"],
    ["Bar at the thighs, soft knees", "Push the hips back, slide down the legs and return"],
    "romanian deadlift form"),
  E("hip-thrust", "הרמת אגן", "Hip thrust", "glutes", "barbell", true,
    ["גב עליון על ספסל, מוט על האגן", "דחוף את האגן מעלה וכווץ ישבן"],
    ["Upper back on a bench, bar over the hips", "Drive the hips up and squeeze the glutes"],
    "hip thrust form"),
  E("glute-bridge", "גשר ישבן", "Glute bridge", "glutes", "bodyweight", false,
    ["שכב על הגב, ברכיים כפופות, כפות רגליים על הרצפה", "דחוף אגן מעלה וכווץ ישבן, רד לאט"],
    ["Lie on your back, knees bent, feet on the floor", "Drive the hips up and squeeze the glutes, lower slowly"],
    "glute bridge form"),
  E("cable-kickback", "בעיטת ישבן בפולי", "Cable glute kickback", "glutes", "cable", false,
    ["רצועה על הקרסול, רכון קלות קדימה", "בעט את הרגל אחורה וכווץ ישבן, חזור לאט"],
    ["Strap on the ankle, lean slightly forward", "Kick the leg back and squeeze the glute, return slowly"],
    "cable glute kickback form"),
  // -- arms (biceps, triceps)
  E("biceps-curl", "כפיפת מרפק", "Biceps curl", "arms", "dumbbell", false,
    ["משקולות לצד הגוף, מרפקים צמודים", "כופף מעלה וכווץ, רד לאט"],
    ["Dumbbells at the sides, elbows pinned", "Curl up and squeeze, lower slowly"],
    "dumbbell biceps curl form"),
  E("hammer-curl", "כפיפת פטיש", "Hammer curl", "arms", "dumbbell", false,
    ["אחיזה ניטרלית, מרפקים צמודים", "כופף מעלה ורד בשליטה"],
    ["Neutral grip, elbows pinned", "Curl up and lower under control"],
    "hammer curl form"),
  E("barbell-curl", "כפיפת מרפק במוט", "Barbell curl", "arms", "barbell", false,
    ["מוט באחיזה תחתונה, מרפקים צמודים", "כופף מעלה וכווץ, רד לאט"],
    ["Bar in an underhand grip, elbows pinned", "Curl up and squeeze, lower slowly"],
    "barbell curl form"),
  E("preacher-curl", "כפיפת מרפק בכיסא כומר", "Preacher curl", "arms", "dumbbell", false,
    ["זרוע על משענת הכיסא, אחיזה תחתונה", "כופף מעלה וכווץ, רד לאט ומלא"],
    ["Arm on the preacher pad, underhand grip", "Curl up and squeeze, lower slow and full"],
    "preacher curl form"),
  E("concentration-curl", "כפיפת ריכוז", "Concentration curl", "arms", "dumbbell", false,
    ["שב, מרפק על פנים הירך", "כופף מעלה וכווץ, רד לאט"],
    ["Sit, elbow against the inner thigh", "Curl up and squeeze, lower slowly"],
    "concentration curl form"),
  E("cable-curl", "כפיפת מרפק בפולי", "Cable curl", "arms", "cable", false,
    ["עמוד מול פולי תחתון, מרפקים צמודים", "כופף מעלה וכווץ, רד לאט"],
    ["Face a low cable, elbows pinned", "Curl up and squeeze, lower slowly"],
    "cable biceps curl form"),
  E("triceps-pushdown", "פשיטת מרפק בפולי", "Triceps pushdown", "arms", "cable", false,
    ["אחוז את החבל, מרפקים צמודים", "דחוף מטה עד יישור וחזור לאט"],
    ["Grab the rope, elbows pinned", "Push down to lockout and return slowly"],
    "triceps pushdown form"),
  E("skullcrusher", "פשיטת מרפק בשכיבה", "Skullcrusher", "arms", "barbell", false,
    ["שכב, מוט מעל המצח, מרפקים למעלה", "הורד אל המצח ופשוט מעלה"],
    ["Lie down, bar over the forehead, elbows up", "Lower to the forehead and extend up"],
    "skullcrusher lying triceps extension form"),
  E("overhead-triceps", "פשיטת מרפק מעל הראש", "Overhead triceps extension", "arms", "dumbbell", false,
    ["משקולת מעל הראש בשתי ידיים", "הורד מאחורי הראש ופשוט מעלה"],
    ["Dumbbell overhead in both hands", "Lower behind the head and extend up"],
    "overhead dumbbell triceps extension form"),
  E("close-grip-bench", "לחיצת חזה אחיזה צרה", "Close-grip bench press", "arms", "barbell", true,
    ["שכב, אחיזה ברוחב כתפיים", "הורד לחזה, מרפקים צמודים, ודחוף מעלה"],
    ["Lie down, shoulder-width grip", "Lower to the chest, elbows tucked, and press up"],
    "close grip bench press form"),
  E("dips", "מקבילים", "Dips", "arms", "bodyweight", true,
    ["תלייה על מקבילים, גוף זקוף", "רד עד 90 מעלות ודחוף מעלה"],
    ["Support on parallel bars, torso upright", "Lower to 90° and press up"],
    "triceps dips form"),
  // -- core
  E("plank", "פלאנק", "Plank", "core", "bodyweight", false,
    ["מרפקים מתחת לכתפיים, גוף ישר", "אסוף ליבה והחזק"],
    ["Elbows under the shoulders, body straight", "Brace the core and hold"],
    "plank proper form"),
  E("side-plank", "פלאנק צדי", "Side plank", "core", "bodyweight", false,
    ["על הצד, מרפק מתחת לכתף, גוף ישר", "הרם אגן והחזק, החלף צד"],
    ["On your side, elbow under the shoulder, body straight", "Lift the hips and hold, switch sides"],
    "side plank form"),
  E("hanging-leg-raise", "הרמת רגליים בתלייה", "Hanging leg raise", "core", "bodyweight", false,
    ["תלייה על מוט", "הרם רגליים ישרות ורד לאט"],
    ["Hang from a bar", "Raise straight legs and lower slowly"],
    "hanging leg raise form"),
  E("crunch", "כפיפות בטן", "Crunch", "core", "bodyweight", false,
    ["שכב, ברכיים כפופות", "כווץ בטן והרם כתפיים, רד לאט"],
    ["Lie down, knees bent", "Crunch and lift the shoulders, lower slowly"],
    "crunch proper form"),
  E("bicycle-crunch", "כפיפות אופניים", "Bicycle crunch", "core", "bodyweight", false,
    ["שכב, ידיים ליד הראש", "הבא מרפק אל הברך הנגדית לסירוגין"],
    ["Lie down, hands by the head", "Bring elbow to the opposite knee, alternating"],
    "bicycle crunch form"),
  E("russian-twist", "סיבובים רוסיים", "Russian twist", "core", "bodyweight", false,
    ["שב עם ברכיים כפופות, גב מוטה אחורה", "סובב את הגו מצד לצד"],
    ["Sit with knees bent, torso leaned back", "Rotate the torso side to side"],
    "russian twist form"),
  E("mountain-climber", "טיפוס הרים", "Mountain climber", "core", "bodyweight", true,
    ["מנח שכיבת סמיכה, ליבה אסופה", "הבא ברכיים אל החזה לסירוגין במהירות"],
    ["Push-up position, core braced", "Drive the knees to the chest, alternating quickly"],
    "mountain climber form"),
  E("dead-bug", "חיפושית מתה", "Dead bug", "core", "bodyweight", false,
    ["שכב, ידיים ורגליים מורמות", "הורד יד ורגל נגדית ואסוף חזרה"],
    ["Lie down, arms and legs raised", "Lower opposite arm and leg, then return"],
    "dead bug exercise form"),
  E("cable-crunch", "כפיפת בטן בפולי", "Cable crunch", "core", "cable", false,
    ["כרע מול פולי עליון, חבל ליד הראש", "כווץ בטן וכופף מטה, חזור לאט"],
    ["Kneel at a high cable, rope by the head", "Crunch down with the abs, return slowly"],
    "cable crunch form"),
  E("ab-wheel", "גלגל בטן", "Ab wheel rollout", "core", "bodyweight", false,
    ["כרע עם הגלגל בידיים", "גלגל קדימה בגוף ישר וחזור"],
    ["Kneel holding the wheel", "Roll forward with a straight body and return"],
    "ab wheel rollout form"),
  // -- full body / cardio
  E("burpee", "ברפי", "Burpee", "fullbody", "bodyweight", true,
    ["שכיבת סמיכה, קפיצה לרגליים", "קפוץ מעלה עם ידיים גבוה"],
    ["Drop to a push-up, jump the feet in", "Jump up with the arms overhead"],
    "burpee proper form"),
  E("kb-swing", "נדנוד קטלבל", "Kettlebell swing", "fullbody", "kettlebell", true,
    ["קטלבל בין הרגליים, דחוף אגן אחורה", "נדנד מעלה בכוח האגן עד גובה החזה"],
    ["Kettlebell between the legs, hips back", "Swing up with the hips to chest height"],
    "kettlebell swing form"),
  E("thruster", "ת'ראסטר", "Thruster", "fullbody", "dumbbell", true,
    ["משקולות בגובה הכתפיים, רד לסקוואט", "התרומם ודחוף את המשקולות מעל הראש"],
    ["Dumbbells at the shoulders, drop to a squat", "Rise and press the dumbbells overhead"],
    "dumbbell thruster form"),
  E("clean-and-press", "הנפה ולחיצה", "Clean and press", "fullbody", "dumbbell", true,
    ["משקולות ליד הרצפה, הנף אל הכתפיים", "דחוף מעל הראש והורד בשליטה"],
    ["Dumbbells near the floor, pull to the shoulders", "Press overhead and lower under control"],
    "dumbbell clean and press form"),
  E("jump-rope", "קפיצה בחבל", "Jump rope", "cardio", "bodyweight", false,
    ["חבל מאחורי הגוף, מרפקים צמודים", "סובב מהשורש כף היד וקפוץ קל"],
    ["Rope behind the body, elbows tucked", "Turn from the wrists and hop lightly"],
    "jump rope for beginners form"),
  E("rowing-machine", "חתירה במכונת אירובי", "Rowing machine", "cardio", "machine", true,
    ["אחוז את הידית, רגליים כפופות", "דחוף ברגליים, משוך אל הבטן, חזור בסדר הפוך"],
    ["Grab the handle, legs bent", "Drive with the legs, pull to the belly, reverse the order"],
    "rowing machine proper form"),
  E("incline-walk", "הליכה בשיפוע", "Incline treadmill walk", "cardio", "machine", false,
    ["הצב שיפוע 8–12%, קצב נוח", "הלך זקוף בלי להיאחז במעקה"],
    ["Set incline 8–12%, easy pace", "Walk tall without holding the rail"],
    "incline treadmill walk fat loss"),
  // -- bodyweight moves, so a home or no-equipment plan is still full
  E("air-squat", "סקוואט משקל גוף", "Bodyweight squat", "legs", "bodyweight", true,
    ["רגליים ברוחב כתפיים, ידיים קדימה", "רד עד שהירכיים מקבילות ודחוף מעלה"],
    ["Feet shoulder-width, arms forward", "Sink to parallel and drive up"],
    "bodyweight squat form"),
  E("bw-lunge", "מספריים משקל גוף", "Bodyweight lunge", "legs", "bodyweight", true,
    ["צעד קדימה, רד עד שהברך האחורית כמעט נוגעת", "דחוף חזרה והחלף רגל"],
    ["Step forward, lower until the back knee nearly touches", "Push back and switch legs"],
    "bodyweight lunge form"),
  E("jump-squat", "סקוואט קפיצה", "Jump squat", "legs", "bodyweight", true,
    ["רד לסקוואט", "התפוצץ מעלה בקפיצה ונחת רך"],
    ["Drop into a squat", "Explode up into a jump and land softly"],
    "jump squat form"),
  E("wall-sit", "ישיבת קיר", "Wall sit", "legs", "bodyweight", false,
    ["גב לקיר, ירכיים במקביל לרצפה", "החזק את המנח"],
    ["Back on the wall, thighs parallel to the floor", "Hold the position"],
    "wall sit form"),
  E("pike-pushup", "שכיבת פייק", "Pike push-up", "shoulders", "bodyweight", true,
    ["מנח V הפוך, ירכיים גבוה", "רד עם הראש לרצפה ודחוף מעלה"],
    ["Inverted-V position, hips high", "Lower the head toward the floor and press up"],
    "pike push up form"),
  E("superman", "סופרמן", "Superman", "back", "bodyweight", false,
    ["שכב על הבטן, ידיים קדימה", "הרם ידיים, חזה ורגליים וכווץ גב תחתון"],
    ["Lie face down, arms forward", "Lift the arms, chest and legs and squeeze the lower back"],
    "superman exercise form"),

  // The rest of the catalogue. A library that stops at 80 moves sends someone
  // back to the app they came from the first time their gym has a machine this
  // one has never heard of, so this covers the variations a commercial gym
  // actually holds: the Smith rack, the cable stations, the plate-loaded
  // machines, the bands, and the cardio floor.
  E("smith-bench", "לחיצת חזה בסמית'", "Smith machine bench press", "chest", "smith", true,
    ["שכב מתחת למוט הסמית' בגובה החזה", "הורד לחזה ודחוף עד יישור מרפקים"],
    ["Lie under the Smith bar at chest height", "Lower to the chest and press to lockout"],
    "smith machine bench press form"),
  E("decline-db-press", "לחיצת חזה תחתון במשקולות", "Decline dumbbell press", "chest", "dumbbell", true,
    ["ספסל בשיפוע שלילי, משקולות מעל החזה התחתון", "הורד לצדדים ודחוף חזרה"],
    ["Decline bench, dumbbells over the lower chest", "Lower to the sides and press back"],
    "decline dumbbell press form"),
  E("incline-cable-fly", "פרפר בכבלים בשיפוע", "Incline cable fly", "chest", "cable", false,
    ["ספסל בשיפוע בין שני כבלים נמוכים", "קרב ידיים בקשת רחבה מעל החזה"],
    ["Incline bench between two low pulleys", "Sweep the hands together in a wide arc"],
    "incline cable fly form"),
  E("landmine-press", "לחיצת לנדמיין", "Landmine press", "chest", "barbell", true,
    ["אחוז את קצה המוט בשתי ידיים מול החזה", "דחוף קדימה ומעלה ביישור מלא"],
    ["Hold the bar end in both hands at the chest", "Press forward and up to full extension"],
    "landmine press form"),
  E("db-pullover", "פולאובר במשקולת", "Dumbbell pullover", "chest", "dumbbell", false,
    ["שכב על ספסל, משקולת מעל החזה בשתי ידיים", "הורד מאחורי הראש בקשת ומשוך חזרה"],
    ["Lie on a bench, one dumbbell over the chest", "Lower behind the head in an arc and pull back"],
    "dumbbell pullover form"),
  E("incline-pushup", "שכיבות סמיכה בשיפוע", "Incline push-up", "chest", "bodyweight", true,
    ["ידיים על ספסל או מדרגה, גוף ישר", "רד לחזה ודחוף חזרה"],
    ["Hands on a bench or step, body straight", "Lower the chest and press back up"],
    "incline push up form"),
  E("decline-pushup", "שכיבות סמיכה עם רגליים מוגבהות", "Decline push-up", "chest", "bodyweight", true,
    ["רגליים על ספסל, ידיים על הרצפה", "רד לחזה ודחוף חזרה"],
    ["Feet on a bench, hands on the floor", "Lower the chest and press back up"],
    "decline push up form"),
  E("diamond-pushup", "שכיבות סמיכה יהלום", "Diamond push-up", "arms", "bodyweight", true,
    ["ידיים צמודות מתחת לחזה בצורת יהלום", "רד עד נגיעה קלה ודחוף חזרה"],
    ["Hands together under the chest in a diamond", "Lower to a light touch and press back"],
    "diamond push up form"),
  E("wide-pushup", "שכיבות סמיכה רחבות", "Wide push-up", "chest", "bodyweight", true,
    ["ידיים רחבות מהכתפיים", "רד בשליטה ודחוף חזרה"],
    ["Hands wider than the shoulders", "Lower under control and press back"],
    "wide grip push up form"),
  E("band-chest-press", "לחיצת חזה בגומייה", "Band chest press", "chest", "band", true,
    ["הגומייה מאחורי הגב, ידיים בגובה החזה", "דחוף קדימה עד יישור"],
    ["Band behind the back, hands at chest height", "Press forward to full extension"],
    "resistance band chest press form"),
  E("plate-press", "לחיצת צלחת", "Plate squeeze press", "chest", "machine", false,
    ["לחץ צלחת בין כפות הידיים מול החזה", "דחוף קדימה תוך לחיצה חזקה"],
    ["Squeeze a plate between the palms at the chest", "Press it forward while squeezing hard"],
    "svend press plate form"),
  E("rack-pull", "ראק פול", "Rack pull", "back", "barbell", true,
    ["מוט על מתלה בגובה הברך", "משוך מעלה ביישור ירכיים וכווץ שכמות"],
    ["Bar on pins at knee height", "Pull up by extending the hips and squeeze the back"],
    "rack pull form"),
  E("pendlay-row", "חתירת פנדליי", "Pendlay row", "back", "barbell", true,
    ["גב מקביל לרצפה, מוט על הרצפה בכל חזרה", "משוך בפיצוץ לבטן והחזר"],
    ["Back parallel to the floor, bar rests each rep", "Pull explosively to the belly and return"],
    "pendlay row form"),
  E("seal-row", "חתירת סיל", "Seal row", "back", "dumbbell", true,
    ["שכב על ספסל מוגבה עם משקולות", "משוך מעלה לשכמות בלי תנופה"],
    ["Lie face down on a raised bench with dumbbells", "Row up to the shoulder blades with no swing"],
    "seal row form"),
  E("chest-supported-row", "חתירה עם תמיכת חזה", "Chest-supported row", "back", "machine", true,
    ["חזה נשען על הכרית", "משוך את הידיות לצלעות וכווץ"],
    ["Chest against the pad", "Pull the handles to the ribs and squeeze"],
    "chest supported row form"),
  E("single-arm-pulldown", "פולי עליון ביד אחת", "Single-arm lat pulldown", "back", "cable", false,
    ["ידית אחת בכבל עליון, ישיבה יציבה", "משוך למטה למרפק צמוד לגוף"],
    ["One handle on a high pulley, sit tall", "Pull down with the elbow close to the body"],
    "single arm lat pulldown form"),
  E("wide-pulldown", "פולי עליון באחיזה רחבה", "Wide-grip pulldown", "back", "cable", true,
    ["אחיזה רחבה במוט העליון", "משוך לחזה העליון ורד בשליטה"],
    ["Wide grip on the bar", "Pull to the upper chest and return slowly"],
    "wide grip lat pulldown form"),
  E("close-pulldown", "פולי עליון באחיזה צרה", "Close-grip pulldown", "back", "cable", true,
    ["אחיזת משולש צרה", "משוך לחזה, מרפקים צמודים"],
    ["Narrow triangle grip", "Pull to the chest with elbows tucked"],
    "close grip lat pulldown form"),
  E("inverted-row", "חתירה הפוכה", "Inverted row", "back", "bodyweight", true,
    ["שכב מתחת למוט נמוך, גוף ישר", "משוך את החזה אל המוט"],
    ["Lie under a low bar, body straight", "Pull the chest to the bar"],
    "inverted row form"),
  E("machine-row", "חתירה במכונה", "Machine row", "back", "machine", true,
    ["ישיבה מול המכונה, חזה לכרית", "משוך את הידיות לצלעות"],
    ["Sit at the machine, chest to the pad", "Pull the handles to the ribs"],
    "machine row form"),
  E("good-morning", "גוד מורנינג", "Good morning", "back", "barbell", true,
    ["מוט על הטרפזים, ברכיים רכות", "רד בירכיים אחורה עד מתיחה וחזור"],
    ["Bar on the traps, knees soft", "Hinge back until you feel a stretch, then stand"],
    "good morning exercise form"),
  E("renegade-row", "חתירת רנגייד", "Renegade row", "back", "dumbbell", true,
    ["פלאנק עם משקולות בשתי הידיים", "משוך אחת בכל פעם בלי לסובב אגן"],
    ["Plank on two dumbbells", "Row one at a time without twisting the hips"],
    "renegade row form"),
  E("band-pulldown", "פולי עליון בגומייה", "Band pulldown", "back", "band", false,
    ["גומייה קשורה גבוה, ברכיים על הרצפה", "משוך למטה עד החזה"],
    ["Band anchored high, kneel underneath", "Pull down to the chest"],
    "band lat pulldown form"),
  E("kroc-row", "חתירת קרוק", "Kroc row", "back", "dumbbell", true,
    ["משקולת כבדה ביד אחת, תמיכה בספסל", "משוך גבוה עם מעט תנופה מבוקרת"],
    ["One heavy dumbbell, brace on a bench", "Row high with a little controlled body english"],
    "kroc row form"),
  E("smith-ohp", "לחיצת כתפיים בסמית'", "Smith shoulder press", "shoulders", "smith", true,
    ["ישיבה מתחת למוט בגובה הסנטר", "דחוף מעלה עד יישור מרפקים"],
    ["Sit under the bar at chin height", "Press overhead to lockout"],
    "smith machine shoulder press form"),
  E("machine-shoulder-press", "לחיצת כתפיים במכונה", "Machine shoulder press", "shoulders", "machine", true,
    ["ידיות בגובה הכתף", "דחוף מעלה ורד בשליטה"],
    ["Handles at shoulder height", "Press up and lower slowly"],
    "machine shoulder press form"),
  E("cable-lateral", "הרחקת כתף בכבל", "Cable lateral raise", "shoulders", "cable", false,
    ["כבל נמוך מאחורי הגוף", "הרם לצד עד גובה כתף"],
    ["Low pulley behind the body", "Raise out to shoulder height"],
    "cable lateral raise form"),
  E("machine-lateral", "הרחקת כתף במכונה", "Machine lateral raise", "shoulders", "machine", false,
    ["מרפקים על הכריות", "דחוף החוצה ומעלה עד גובה כתף"],
    ["Elbows against the pads", "Drive out and up to shoulder height"],
    "machine lateral raise form"),
  E("seated-db-press", "לחיצת כתפיים בישיבה", "Seated dumbbell press", "shoulders", "dumbbell", true,
    ["ישיבה עם גב נתמך, משקולות בגובה האוזן", "דחוף מעלה עד כמעט מגע"],
    ["Seated with back supported, dumbbells at ear height", "Press up until they almost touch"],
    "seated dumbbell shoulder press form"),
  E("push-press", "פוש פרס", "Push press", "shoulders", "barbell", true,
    ["כפיפת ברכיים קצרה", "נצל את התנופה ודחוף את המוט מעל הראש"],
    ["A short dip at the knees", "Use the drive to press the bar overhead"],
    "push press form"),
  E("reverse-pec-deck", "פרפר הפוך במכונה", "Reverse pec deck", "shoulders", "machine", false,
    ["חזה לכרית, ידיים קדימה", "פתח לצדדים וכווץ שכמות"],
    ["Chest on the pad, arms forward", "Open out to the sides and squeeze"],
    "reverse pec deck form"),
  E("cable-rear-delt", "פרפר אחורי בכבלים", "Cable rear delt fly", "shoulders", "cable", false,
    ["כבלים מוצלבים בגובה כתף", "פתח לצדדים בקשת רחבה"],
    ["Cables crossed at shoulder height", "Open out to the sides in a wide arc"],
    "cable rear delt fly form"),
  E("band-lateral", "הרחקת כתף בגומייה", "Band lateral raise", "shoulders", "band", false,
    ["דרוך על הגומייה, ידיים לצדדים", "הרם עד גובה כתף"],
    ["Stand on the band, hands at the sides", "Raise to shoulder height"],
    "band lateral raise form"),
  E("plate-front-raise", "הרמת צלחת קדימה", "Plate front raise", "shoulders", "machine", false,
    ["צלחת בשתי ידיים מול הירכיים", "הרם קדימה עד גובה עיניים"],
    ["Plate in both hands at the hips", "Raise forward to eye level"],
    "plate front raise form"),
  E("cuban-press", "לחיצה קובנית", "Cuban press", "shoulders", "dumbbell", false,
    ["חתירה גבוהה, סובב חוץ ואז לחץ מעלה"],
    ["High pull, rotate out, then press overhead"],
    "cuban press form"),
  E("smith-squat", "סקוואט בסמית'", "Smith machine squat", "legs", "smith", true,
    ["מוט על הטרפזים, רגליים מעט קדימה", "רד עד ירך מקבילה וקום"],
    ["Bar on the traps, feet slightly forward", "Squat to parallel and stand"],
    "smith machine squat form"),
  E("box-squat", "סקוואט לקופסה", "Box squat", "legs", "barbell", true,
    ["ארגז מאחוריך בגובה מקביל", "שב בשליטה, עצור, וקום"],
    ["Box behind you at parallel", "Sit under control, pause, then stand"],
    "box squat form"),
  E("sissy-squat", "סיסי סקוואט", "Sissy squat", "legs", "bodyweight", false,
    ["עקבים מוגבהים, גוף ישר מהברך", "רד אחורה על הברכיים וחזור"],
    ["Heels raised, body straight from the knee", "Lean back over the knees and return"],
    "sissy squat form"),
  E("single-leg-press", "לחיצת רגל אחת", "Single-leg press", "legs", "machine", true,
    ["רגל אחת במרכז הפלטה", "דחוף עד כמעט יישור ורד לתשעים"],
    ["One foot centred on the platform", "Press to near lockout and return to 90°"],
    "single leg press form"),
  E("seated-leg-curl", "כפיפת ברך בישיבה", "Seated leg curl", "legs", "machine", false,
    ["ישיבה עם כרית מעל הקרסול", "כופף עד הסוף וכווץ ירך אחורית"],
    ["Seated with the pad above the ankles", "Curl all the way and squeeze the hamstrings"],
    "seated leg curl form"),
  E("lying-leg-curl", "כפיפת ברך בשכיבה", "Lying leg curl", "legs", "machine", false,
    ["שכיבה על הבטן, כרית מעל העקבים", "כופף לישבן ורד לאט"],
    ["Face down, pad above the heels", "Curl to the glutes and lower slowly"],
    "lying leg curl form"),
  E("nordic-curl", "נורדיק קרל", "Nordic hamstring curl", "legs", "bodyweight", false,
    ["ברכיים על מזרן, קרסוליים מקובעים", "רד קדימה לאט ככל שאפשר"],
    ["Kneel with the ankles anchored", "Lower forward as slowly as you can"],
    "nordic hamstring curl form"),
  E("sumo-deadlift", "דדליפט סומו", "Sumo deadlift", "legs", "barbell", true,
    ["עמידה רחבה, אחיזה בין הרגליים", "דחוף רצפה ויישר ירכיים"],
    ["Wide stance, grip inside the legs", "Push the floor away and lock the hips"],
    "sumo deadlift form"),
  E("trap-bar-deadlift", "דדליפט במוט משושה", "Trap bar deadlift", "legs", "barbell", true,
    ["עמידה במרכז המוט המשושה", "דחוף רצפה וקום ביישור מלא"],
    ["Stand in the middle of the trap bar", "Push the floor and stand tall"],
    "trap bar deadlift form"),
  E("stiff-leg-deadlift", "דדליפט רגליים ישרות", "Stiff-leg deadlift", "legs", "barbell", true,
    ["ברכיים כמעט ישרות", "רד עם המוט צמוד לרגליים עד מתיחה"],
    ["Knees almost straight", "Lower the bar along the legs to a stretch"],
    "stiff leg deadlift form"),
  E("single-leg-rdl", "דדליפט רומני על רגל אחת", "Single-leg RDL", "legs", "dumbbell", true,
    ["עמידה על רגל אחת, משקולת ביד הנגדית", "רד בירך עם גב ישר וחזור"],
    ["Stand on one leg, weight in the opposite hand", "Hinge with a flat back and return"],
    "single leg romanian deadlift form"),
  E("reverse-lunge", "מכרעים אחורה", "Reverse lunge", "legs", "dumbbell", true,
    ["צעד אחורה ורד עד ברך כמעט לרצפה", "דחוף חזרה לעמידה"],
    ["Step back and drop the knee to just off the floor", "Drive back to standing"],
    "reverse lunge form"),
  E("lateral-lunge", "מכרעים לצד", "Lateral lunge", "legs", "bodyweight", true,
    ["צעד רחב לצד, שקע על אותה רגל", "דחוף חזרה למרכז"],
    ["Step wide to the side and sit into that leg", "Push back to the middle"],
    "lateral lunge form"),
  E("curtsy-lunge", "מכרע קרטסי", "Curtsy lunge", "glutes", "dumbbell", true,
    ["צעד אלכסוני מאחורי הרגל השנייה", "רד ודחוף חזרה"],
    ["Step diagonally behind the other leg", "Lower and drive back up"],
    "curtsy lunge form"),
  E("pistol-squat", "סקוואט פיסטול", "Pistol squat", "legs", "bodyweight", true,
    ["עמידה על רגל אחת, השנייה קדימה", "רד עד הסוף וקום"],
    ["Stand on one leg, the other out front", "Squat all the way down and stand"],
    "pistol squat form"),
  E("standing-calf", "הרמת עקבים במכונה", "Machine calf raise", "legs", "machine", false,
    ["כתפיים תחת הכריות, קדמות כפות על המדרגה", "עלה גבוה ורד למתיחה מלאה"],
    ["Shoulders under the pads, toes on the step", "Rise high and lower to a full stretch"],
    "standing calf raise machine form"),
  E("donkey-calf", "הרמת עקבים חמור", "Donkey calf raise", "legs", "machine", false,
    ["ירכיים כפופות, משקל על האגן", "עלה על קצות האצבעות ורד"],
    ["Hips bent, weight over the pelvis", "Rise onto the toes and lower"],
    "donkey calf raise form"),
  E("adductor-machine", "מקרב ירך במכונה", "Adductor machine", "legs", "machine", false,
    ["ישיבה עם כריות בפנים הירכיים", "סגור רגליים וכווץ"],
    ["Seated with pads inside the thighs", "Squeeze the legs together"],
    "adductor machine form"),
  E("abductor-machine", "מרחיק ירך במכונה", "Abductor machine", "glutes", "machine", false,
    ["ישיבה עם כריות בחוץ הירכיים", "פתח רגליים החוצה וכווץ ישבן"],
    ["Seated with pads outside the thighs", "Push the legs apart and squeeze the glutes"],
    "abductor machine form"),
  E("single-leg-hip-thrust", "הרמת אגן על רגל אחת", "Single-leg hip thrust", "glutes", "bodyweight", false,
    ["גב על ספסל, רגל אחת באוויר", "הרם אגן עד יישור וכווץ"],
    ["Back on a bench, one leg in the air", "Drive the hips up and squeeze"],
    "single leg hip thrust form"),
  E("frog-pump", "פרוג פאמפ", "Frog pump", "glutes", "bodyweight", false,
    ["שכיבה, כפות רגליים צמודות וברכיים החוצה", "הרם אגן וכווץ ישבן"],
    ["Lie down, soles together and knees out", "Lift the hips and squeeze the glutes"],
    "frog pump glute form"),
  E("pull-through", "משיכת כבל בין הרגליים", "Cable pull-through", "glutes", "cable", true,
    ["גב לכבל נמוך, חבל בין הרגליים", "רד בירך ויישר בכוח הישבן"],
    ["Back to a low pulley, rope between the legs", "Hinge back and stand with the glutes"],
    "cable pull through form"),
  E("kb-deadlift", "דדליפט קטלבל", "Kettlebell deadlift", "glutes", "kettlebell", true,
    ["קטלבל בין הרגליים", "רד בירך, אחוז וקום ביישור"],
    ["Kettlebell between the feet", "Hinge, grip and stand tall"],
    "kettlebell deadlift form"),
  E("glute-ham-raise", "הרמת ירך אחורית", "Glute-ham raise", "glutes", "bodyweight", true,
    ["קרסוליים מקובעים, גוף ישר", "רד קדימה ומשוך חזרה עם הירך"],
    ["Ankles anchored, body straight", "Lower forward and pull back with the hamstrings"],
    "glute ham raise form"),
  E("banded-walk", "הליכה עם גומייה", "Banded lateral walk", "glutes", "band", false,
    ["גומייה מעל הברכיים, חצי סקוואט", "צעד לצדדים בלי לסגור ברכיים"],
    ["Band above the knees, half squat", "Step sideways without letting the knees cave"],
    "banded lateral walk form"),
  E("incline-db-curl", "כפיפת מרפק בשיפוע", "Incline dumbbell curl", "arms", "dumbbell", false,
    ["ישיבה בשיפוע, ידיים תלויות אחורה", "כופף מעלה בלי להזיז מרפק"],
    ["Sit on an incline, arms hanging back", "Curl up without moving the elbow"],
    "incline dumbbell curl form"),
  E("spider-curl", "ספיידר קרל", "Spider curl", "arms", "dumbbell", false,
    ["חזה על ספסל בשיפוע, ידיים תלויות", "כופף מעלה וכווץ בשיא"],
    ["Chest on an incline bench, arms hanging", "Curl up and squeeze at the top"],
    "spider curl form"),
  E("reverse-curl", "כפיפת מרפק באחיזה הפוכה", "Reverse curl", "arms", "barbell", false,
    ["אחיזה עליונה במוט", "כופף מעלה עם שורש יד ישר"],
    ["Overhand grip on the bar", "Curl up keeping the wrists straight"],
    "reverse curl form"),
  E("zottman-curl", "כפיפת זוטמן", "Zottman curl", "arms", "dumbbell", false,
    ["כופף באחיזה תחתונה", "סובב למעלה ורד באחיזה עליונה"],
    ["Curl up with palms up", "Rotate at the top and lower palms down"],
    "zottman curl form"),
  E("ez-curl", "כפיפת מרפק במוט EZ", "EZ-bar curl", "arms", "barbell", false,
    ["אחיזה בזוויות המוט", "כופף מעלה בלי תנופה"],
    ["Grip the angled part of the bar", "Curl up with no swing"],
    "ez bar curl form"),
  E("drag-curl", "דראג קרל", "Drag curl", "arms", "barbell", false,
    ["גרור את המוט לאורך הגוף", "מרפקים אחורה, כווץ בשיא"],
    ["Drag the bar up along the body", "Elbows back, squeeze at the top"],
    "drag curl form"),
  E("machine-curl", "כפיפת מרפק במכונה", "Machine biceps curl", "arms", "machine", false,
    ["מרפקים על הכרית", "כופף עד הסוף ורד לאט"],
    ["Elbows on the pad", "Curl all the way and lower slowly"],
    "machine biceps curl form"),
  E("rope-pushdown", "פשיטת מרפק בחבל", "Rope pushdown", "arms", "cable", false,
    ["חבל בכבל עליון, מרפקים צמודים", "דחוף למטה ופתח את החבל בסוף"],
    ["Rope on a high pulley, elbows tucked", "Push down and split the rope at the bottom"],
    "rope pushdown form"),
  E("single-arm-pushdown", "פשיטת מרפק ביד אחת", "Single-arm pushdown", "arms", "cable", false,
    ["ידית אחת, כף יד למעלה או למטה", "פשוט את המרפק עד הסוף"],
    ["One handle, palm up or down", "Extend the elbow fully"],
    "single arm triceps pushdown form"),
  E("db-overhead-extension", "פשיטת מרפק מעל הראש בחבל", "Overhead rope extension", "arms", "cable", false,
    ["גב לכבל, חבל מאחורי הראש", "פשוט קדימה ומעלה עד יישור מלא"],
    ["Back to the pulley, rope behind the head", "Extend forward and up to full lockout"],
    "overhead rope triceps extension form"),
  E("bench-dip", "מקבילים על ספסל", "Bench dip", "arms", "bodyweight", true,
    ["ידיים על ספסל מאחור, רגליים קדימה", "רד עד תשעים ודחוף חזרה"],
    ["Hands on a bench behind you, legs out", "Lower to 90° and press back up"],
    "bench dip form"),
  E("triceps-kickback", "בעיטת יד אחורה", "Triceps kickback", "arms", "dumbbell", false,
    ["גב מקביל לרצפה, מרפק צמוד", "פשוט את היד אחורה וכווץ"],
    ["Back parallel to the floor, elbow tucked", "Extend the arm back and squeeze"],
    "triceps kickback form"),
  E("jm-press", "JM פרס", "JM press", "arms", "barbell", true,
    ["שכיבה, מוט לכיוון הצוואר במסלול קצר", "דחוף חזרה בעיקר בטרייספס"],
    ["Lie down, bar tracks toward the neck", "Press back mostly with the triceps"],
    "jm press form"),
  E("band-curl", "כפיפת מרפק בגומייה", "Band curl", "arms", "band", false,
    ["דרוך על הגומייה", "כופף מעלה נגד ההתנגדות"],
    ["Stand on the band", "Curl up against the resistance"],
    "resistance band biceps curl form"),
  E("wrist-curl", "כפיפת שורש יד", "Wrist curl", "forearms", "dumbbell", false,
    ["אמות על הברכיים, כפות למעלה", "כופף שורש יד מעלה ורד"],
    ["Forearms on the thighs, palms up", "Curl the wrists up and lower"],
    "wrist curl form"),
  E("reverse-wrist-curl", "פשיטת שורש יד", "Reverse wrist curl", "forearms", "dumbbell", false,
    ["אמות על הברכיים, כפות למטה", "הרם את גב כף היד"],
    ["Forearms on the thighs, palms down", "Lift the back of the hands"],
    "reverse wrist curl form"),
  E("farmers-walk", "הליכת החקלאי", "Farmer's walk", "forearms", "dumbbell", true,
    ["משקל כבד בכל יד, כתפיים אחורה", "לך ישר במרחק קבוע"],
    ["Heavy weight in each hand, shoulders back", "Walk a set distance staying tall"],
    "farmers walk form"),
  E("plate-pinch", "אחיזת צלחות", "Plate pinch hold", "forearms", "machine", false,
    ["צבוט שתי צלחות בין האצבעות", "החזק כמה שיותר"],
    ["Pinch two plates between the fingers", "Hold for as long as you can"],
    "plate pinch grip hold"),
  E("towel-hang", "תלייה על מגבת", "Towel hang", "forearms", "bodyweight", false,
    ["העבר מגבת מעל מוט מתח ואחוז בשני קצותיה", "תלה והחזק — אחיזה עבה שורפת אמות"],
    ["Loop a towel over a pull-up bar and hold both ends", "Hang and hold — the thick grip torches the forearms"],
    "towel hang grip training"),
  E("wrist-roller", "גלגלת שורש יד", "Wrist roller", "forearms", "machine", false,
    ["מוט עם חבל ומשקל, ידיים ישרות קדימה", "גלגל את המשקל מעלה ואז למטה בשליטה"],
    ["A bar with a rope and weight, arms straight out", "Roll the weight up, then back down under control"],
    "wrist roller forearm exercise"),
  E("dead-hang", "תלייה על מוט", "Dead hang", "forearms", "bodyweight", false,
    ["תלייה על מוט מתח בזרועות ישרות", "החזק וכתפיים לא מתות"],
    ["Hang from a bar with straight arms", "Hold with the shoulders active"],
    "dead hang form"),
  E("hollow-hold", "הולו הולד", "Hollow hold", "core", "bodyweight", false,
    ["שכיבה, גב תחתון צמוד לרצפה", "הרם כתפיים ורגליים והחזק"],
    ["Lie down, low back pressed into the floor", "Lift the shoulders and legs and hold"],
    "hollow hold form"),
  E("v-up", "V-אפ", "V-up", "core", "bodyweight", false,
    ["שכיבה עם ידיים מעל הראש", "הרם ידיים ורגליים לפגישה מעל הבטן"],
    ["Lie with the arms overhead", "Lift the arms and legs to meet over the belly"],
    "v up exercise form"),
  E("toes-to-bar", "רגליים למוט", "Toes to bar", "core", "bodyweight", true,
    ["תלייה על מוט", "הרם רגליים ישרות עד נגיעה במוט"],
    ["Hang from a bar", "Raise straight legs to touch the bar"],
    "toes to bar form"),
  E("decline-situp", "כפיפות בטן בשיפוע", "Decline sit-up", "core", "bodyweight", false,
    ["רגליים מקובעות בספסל שלילי", "עלה בשליטה ורד לאט"],
    ["Feet anchored on a decline bench", "Sit up under control and lower slowly"],
    "decline sit up form"),
  E("woodchop", "חיתוך עץ בכבל", "Cable woodchop", "core", "cable", false,
    ["כבל גבוה, ידיים ישרות", "סובב אלכסונית למטה מהאגן"],
    ["High pulley, arms straight", "Rotate diagonally down from the hips"],
    "cable woodchop form"),
  E("pallof-press", "פאלוף פרס", "Pallof press", "core", "cable", false,
    ["עמידה בצד לכבל בגובה חזה", "דחוף קדימה בלי לתת לגוף להסתובב"],
    ["Stand side-on to a chest-height cable", "Press out without letting the torso rotate"],
    "pallof press form"),
  E("weighted-plank", "פלאנק עם משקל", "Weighted plank", "core", "bodyweight", false,
    ["פלאנק עם צלחת על הגב", "החזק גוף ישר לגמרי"],
    ["Plank with a plate on the back", "Hold a completely straight line"],
    "weighted plank form"),
  E("side-bend", "כפיפה צידית", "Dumbbell side bend", "core", "dumbbell", false,
    ["משקולת ביד אחת", "רד לצד ועלה בכוח האלכסונים"],
    ["Dumbbell in one hand", "Bend to the side and come up with the obliques"],
    "dumbbell side bend form"),
  E("flutter-kick", "בעיטות רפרוף", "Flutter kick", "core", "bodyweight", false,
    ["שכיבה, ידיים מתחת לאגן", "בעט לסירוגין עם רגליים ישרות"],
    ["Lie down, hands under the hips", "Kick alternately with straight legs"],
    "flutter kick form"),
  E("reverse-crunch", "כפיפת בטן הפוכה", "Reverse crunch", "core", "bodyweight", false,
    ["שכיבה, ברכיים כפופות", "גלגל אגן מעלה לכיוון החזה"],
    ["Lie down, knees bent", "Roll the hips up toward the chest"],
    "reverse crunch form"),
  E("l-sit", "L-סיט", "L-sit", "core", "bodyweight", false,
    ["ידיים על מקבילים או הרצפה", "הרם רגליים ישרות לזווית ישרה והחזק"],
    ["Hands on parallettes or the floor", "Lift straight legs to 90° and hold"],
    "l sit form"),
  E("landmine-twist", "סיבוב לנדמיין", "Landmine twist", "core", "barbell", false,
    ["קצה המוט בשתי ידיים מול החזה", "סובב מצד לצד עם אגן יציב"],
    ["Bar end in both hands at the chest", "Rotate side to side with steady hips"],
    "landmine twist form"),
  E("hanging-knee-raise", "הרמת ברכיים בתלייה", "Hanging knee raise", "core", "bodyweight", false,
    ["תלייה על מוט", "הרם ברכיים לחזה בלי תנופה"],
    ["Hang from a bar", "Raise the knees to the chest with no swing"],
    "hanging knee raise form"),
  E("turkish-getup", "טורקיש גט-אפ", "Turkish get-up", "fullbody", "kettlebell", true,
    ["קטלבל ביד ישרה מעל", "קום לעמידה בשלבים ורד חזרה"],
    ["Kettlebell locked out overhead", "Stand up step by step and reverse it"],
    "turkish get up form"),
  E("power-clean", "פאוור קלין", "Power clean", "fullbody", "barbell", true,
    ["משוך מהרצפה בפיצוץ", "קבל את המוט על הכתפיים בחצי סקוואט"],
    ["Pull explosively from the floor", "Catch the bar on the shoulders in a quarter squat"],
    "power clean form"),
  E("snatch", "סנאץ'", "Snatch", "fullbody", "barbell", true,
    ["אחיזה רחבה, משיכה מהירה מהרצפה", "קבל את המוט מעל הראש בזרועות ישרות"],
    ["Wide grip, fast pull from the floor", "Catch the bar overhead with straight arms"],
    "barbell snatch form"),
  E("kb-clean", "קלין קטלבל", "Kettlebell clean", "fullbody", "kettlebell", true,
    ["נדנוד קצר מבין הרגליים", "הפוך את הקטלבל לרק פוזיציה"],
    ["A short swing from between the legs", "Turn the bell over into the rack position"],
    "kettlebell clean form"),
  E("kb-snatch", "סנאץ' קטלבל", "Kettlebell snatch", "fullbody", "kettlebell", true,
    ["נדנוד חזק", "המשך ישר מעל הראש ביד ישרה"],
    ["A powerful swing", "Punch straight overhead to a locked arm"],
    "kettlebell snatch form"),
  E("wall-ball", "ווֹל בול", "Wall ball", "fullbody", "machine", true,
    ["סקוואט עם כדור כבד", "קום וזרוק לגובה על הקיר"],
    ["Squat holding a medicine ball", "Stand and throw it high on the wall"],
    "wall ball form"),
  E("sled-push", "דחיפת מזחלת", "Sled push", "fullbody", "machine", true,
    ["ידיים על המזחלת, גוף נטוי קדימה", "דחוף בצעדים קצרים וחזקים"],
    ["Hands on the sled, body leaning forward", "Drive with short powerful steps"],
    "sled push form"),
  E("man-maker", "מאן מייקר", "Man maker", "fullbody", "dumbbell", true,
    ["ברפי עם משקולות וחתירה בכל צד", "קום ולחץ מעל הראש"],
    ["Burpee on dumbbells with a row each side", "Stand and press overhead"],
    "man maker exercise form"),
  E("devil-press", "דוויל פרס", "Devil press", "fullbody", "dumbbell", true,
    ["ברפי עם משקולות בידיים", "העף אותן מעל הראש בתנועה אחת"],
    ["Burpee holding the dumbbells", "Swing them overhead in one motion"],
    "devil press form"),
  E("treadmill-run", "ריצה על הליכון", "Treadmill run", "cardio", "machine", true,
    ["בחר קצב שאתה יכול להחזיק", "רוץ בזמן קבוע ושמור על נשימה"],
    ["Pick a pace you can hold", "Run for a set time and keep the breathing steady"],
    "treadmill running form"),
  E("stationary-bike", "אופני כושר", "Stationary bike", "cardio", "machine", true,
    ["כוון את גובה האוכף לרגל כמעט ישרה", "דווש בקצב אחיד"],
    ["Set the saddle so the leg is almost straight", "Pedal at an even pace"],
    "stationary bike proper form"),
  E("elliptical", "אליפטיקל", "Elliptical", "cardio", "machine", true,
    ["עמידה זקופה, ידיים על הידיות", "שמור על קצב אחיד"],
    ["Stand tall, hands on the handles", "Keep a steady rhythm"],
    "elliptical machine form"),
  E("stair-master", "מדרגות", "Stair climber", "cardio", "machine", true,
    ["אל תישען על המעקה", "עלה בצעד מלא ובקצב קבוע"],
    ["Don't lean on the rail", "Take full steps at a steady pace"],
    "stair climber form"),
  E("assault-bike", "אופני התנגדות", "Assault bike", "cardio", "machine", true,
    ["דחוף ומשוך עם הידיים יחד עם הרגליים", "אינטרוולים קצרים וחזקים"],
    ["Push and pull the handles with the legs", "Short hard intervals"],
    "assault bike form"),
  E("ski-erg", "סקי ארג", "Ski erg", "cardio", "machine", true,
    ["משוך למטה מהחזה עם כל הגוף", "החזר לאט למעלה"],
    ["Pull down from the chest with the whole body", "Return slowly to the top"],
    "ski erg form"),
  E("swimming", "שחייה", "Swimming", "cardio", "bodyweight", true,
    ["בחר סגנון נוח", "שחה בסטים עם מנוחה קצרה"],
    ["Pick a stroke you're comfortable with", "Swim in sets with short rests"],
    "freestyle swimming technique"),
  E("sprint-intervals", "ספרינטים", "Sprint intervals", "cardio", "bodyweight", true,
    ["חימום מלא לפני", "רוץ חזק 20-30 שניות ונוח"],
    ["Warm up fully first", "Run hard for 20–30 seconds, then rest"],
    "sprint interval training form"),
  E("box-jump", "קפיצה לקופסה", "Box jump", "cardio", "bodyweight", true,
    ["ארגז בגובה בטוח", "קפוץ ונחת רך, רד בהליכה"],
    ["A box at a safe height", "Jump and land softly, step back down"],
    "box jump form"),
  E("battle-ropes", "חבלי קרב", "Battle ropes", "cardio", "machine", true,
    ["חצי סקוואט, חבל בכל יד", "הכה גלים מהירים לזמן קצוב"],
    ["Half squat, a rope in each hand", "Drive fast waves for a set time"],
    "battle ropes form"),
];

/** Everyday muscle groups that a plan cycles through. */
export const MUSCLES: Muscle[] = [
  "chest", "back", "shoulders", "legs", "glutes", "arms", "forearms", "core",
  "fullbody", "cardio",
];

// Opening a demo lives in ./video: what the app opens is the exact clip when
// it can be resolved, and only then the search page — see that file.
