// Generated by scripts/bundle-food-photos.mjs — do not edit by hand.
// A real photograph of each food, from Wikimedia Commons, shipped inside the
// app: the tiles of "your plate", the diary and the search. Nothing requested.
import type { BundledPhoto } from "./mealPhotoAssets";

export const BUNDLED_FOOD_PHOTOS: Record<string, BundledPhoto> = {
};
