/**
 * The rest of what people actually eat and buy.
 *
 * The first library was ingredients for cooking. A real day also has a pita
 * with falafel, a slice of pizza, a coffee, a bag of Bamba and a schnitzel —
 * and a real shopping list has salt, oil and cola on it. Anything the kitchen
 * does not know is priced by a category guess and listed as "unknown", which
 * is exactly the complaint: "it doesn't recognise what I wrote". So this file
 * adds the foods, drinks, dishes, sweets and seasonings of an ordinary Israeli
 * week, each with everything the rest of the app needs:
 *
 *  - names in both languages and the spellings people type;
 *  - per-100 g nutrition (USDA FoodData Central where a twin exists, typical
 *    Israeli label values otherwise), with the same basis rules and Atwater
 *    check as ./nutrition.ts;
 *  - one sensible portion, in grams and in household words;
 *  - its dietary class — meat, fish, dairy, not kosher, gluten — so the
 *    filters are data rather than a hand-kept list that falls behind;
 *  - what the "can I eat this?" score should know about it (fried, sugary,
 *    wholegrain...);
 *  - the phrase its photograph is found by.
 *
 * Pure data. `data.ts` merges it into FOODS, NUTRITION and the portions.
 */
import type { Basis, Per100Row } from "./nutrition";

/** A seasoning, condiment, drink or sweet — things on a list or in a diary
 * that are never the base of a plate. */
export type ExtraTag = "spice" | "drink" | "sweet";

export type ExtraRow = {
  id: string;
  tags: string[];
  he: string;
  en: string;
  match: string[];
  shape: "round" | "long" | "leaf" | "grain" | "slice" | "blob" | "drop";
  color: string;
  n: Per100Row;
  portion: { g: number; he: string; en: string };
  /**
   * Dietary class, one letter each:
   *  M meat · F kosher fish · D dairy · T non-kosher meat · S non-kosher sea
   *  creature · G contains gluten.
   */
  diet: string;
  /**
   * What the score reads, one letter each:
   *  p processed/fried · s added sugar · r refined starch · w wholegrain ·
   *  l legume · o good fat · n lean protein · x saturated fat · m red meat ·
   *  y salty · e energy dense · k fermented · f high fibre · 3 oily fish ·
   *  4 lean fish.
   */
  score: string;
  /** English phrase for its photograph on Wikimedia Commons. */
  photo: string;
};

const n = (kcal: number, protein: number, carbs: number, fat: number, basis: Basis, alcohol?: number): Per100Row =>
  alcohol ? { kcal, protein, carbs, fat, basis, alcohol } : { kcal, protein, carbs, fat, basis };
const p = (g: number, he: string, en: string) => ({ g, he, en });

const X = (
  id: string,
  tags: string[],
  he: string,
  en: string,
  match: string[],
  shape: ExtraRow["shape"],
  color: string,
  nut: Per100Row,
  portion: ExtraRow["portion"],
  diet: string,
  score: string,
  photo: string,
): ExtraRow => ({ id, tags, he, en, match, shape, color, n: nut, portion, diet, score, photo });

export const EXTRA_FOODS: ExtraRow[] = [
  // ------------------------------------------------ Israeli & street food
  X("falafel", ["protein", "carb"], "פלאפל", "falafel", ["פלאפל", "כדורי פלאפל", "falafel"], "round", "#8A6A2F",
    n(333, 13.3, 31.8, 17.8, "asSold"), p(85, "5 כדורים", "5 balls"), "", "pl", "falafel balls"),
  X("falafelPita", ["carb", "protein"], "פלאפל בפיתה", "falafel in pita", ["פלאפל בפיתה", "מנת פלאפל", "חצי מנה פלאפל", "falafel pita", "falafel sandwich"], "round", "#B08A4A",
    n(230, 7, 28, 10, "asSold"), p(350, "מנה בפיתה", "1 pita"), "G", "pr", "falafel pita sandwich"),
  X("shawarma", ["protein"], "שווארמה", "shawarma", ["שווארמה", "שוארמה", "שווארמת הודו", "שווארמה בצלחת", "shawarma", "shawerma"], "blob", "#B5753C",
    n(215, 25, 3, 11.5, "cooked"), p(150, "מנה בצלחת", "a plate portion"), "M", "py", "shawarma meat"),
  X("shawarmaPita", ["carb", "protein"], "שווארמה בפיתה", "shawarma in pita", ["שווארמה בפיתה", "שווארמה בלאפה", "שוארמה בפיתה", "שוארמה בלאפה", "shawarma pita", "shawarma wrap"], "round", "#C08850",
    n(230, 13, 22, 10, "asSold"), p(300, "מנה בפיתה", "1 pita"), "MG", "ry", "shawarma sandwich"),
  X("sabich", ["carb", "veg"], "סביח", "sabich", ["סביח", "sabich"], "round", "#9C6B4A",
    n(200, 6, 22, 10, "asSold"), p(300, "מנה בפיתה", "1 pita"), "G", "r", "sabich sandwich"),
  X("schnitzel", ["protein", "carb"], "שניצל", "schnitzel", ["שניצל", "שניצלים", "שניצל עוף", "schnitzel"], "blob", "#D09A4E",
    n(258, 20, 12, 14.5, "cooked"), p(150, "שניצל אחד", "1 schnitzel"), "MG", "p", "chicken schnitzel"),
  X("chickenThigh", ["protein"], "פרגית", "chicken thigh", ["פרגית", "פרגיות", "ירכיים", "כרעיים", "שוקיים", "כנפיים", "chicken thigh", "chicken thighs", "drumsticks", "pargit"], "blob", "#C99466",
    n(209, 26, 0, 10.9, "cooked"), p(150, "2 פרגיות", "2 thighs"), "M", "", "grilled chicken thighs"),
  X("chickenNuggets", ["protein", "carb"], "נאגטס", "chicken nuggets", ["נאגטס", "נגטס", "nuggets", "chicken nuggets"], "blob", "#D8A450",
    n(296, 15.3, 15.8, 19.3, "cooked"), p(100, "6 נאגטס", "6 nuggets"), "MG", "px", "chicken nuggets"),
  X("burekas", ["carb", "dairy"], "בורקס", "bourekas", ["בורקס", "בורקס גבינה", "בורקס תפוחי אדמה", "בורקסים", "bourekas", "burekas", "borekas"], "slice", "#DDB064",
    n(360, 9, 30, 22.5, "asSold"), p(100, "בורקס אחד", "1 pastry"), "DG", "px", "bourekas pastry"),
  X("malawach", ["carb"], "מלוואח", "malawach", ["מלוואח", "מלאווח", "malawach"], "round", "#D7A95B",
    n(330, 6, 36, 18, "asSold"), p(125, "מלוואח אחד", "1 malawach"), "G", "px", "malawach"),
  X("jachnun", ["carb"], "ג'חנון", "jachnun", ["ג'חנון", "ג׳חנון", "גחנון", "jachnun"], "long", "#B87A3A",
    n(340, 6, 40, 17, "asSold"), p(150, "2 גלילים", "2 rolls"), "G", "px", "jachnun yemenite"),
  X("kubbeh", ["protein", "carb"], "קובה", "kubbeh", ["קובה", "קובות", "kubbeh", "kibbeh"], "round", "#A8703A",
    n(250, 11, 22, 13, "cooked"), p(120, "2 קובות", "2 kubbeh"), "MG", "p", "kibbeh"),
  X("ptitim", ["carb"], "פתיתים", "ptitim", ["פתיתים", "פתיתים אפויים", "ptitim", "israeli couscous"], "grain", "#E6CF8E",
    n(357, 12, 74, 1.5, "dry"), p(75, "חצי כוס יבש", "1/2 cup dry"), "G", "r", "israeli couscous ptitim"),
  X("shakshukaDish", ["protein", "veg"], "שקשוקה", "shakshuka", ["שקשוקה", "shakshuka", "shakshouka"], "blob", "#D2532E",
    n(110, 6.5, 5, 7, "cooked"), p(300, "מחבת לאחד", "a one-person pan"), "", "", "shakshouka pan"),
  X("omelette", ["protein"], "חביתה", "omelette", ["חביתה", "חביתות", "ביצה מקושקשת", "ביצים מקושקשות", "omelette", "omelet", "scrambled eggs"], "round", "#F2CB4E",
    n(154, 11, 0.6, 12, "cooked"), p(120, "חביתה מ־2 ביצים", "a 2-egg omelette"), "", "n", "omelette plate"),
  X("meatballs", ["protein"], "קציצות", "meatballs", ["קציצות", "קציצות בשר", "קציצות ברוטב", "קציצה", "meatballs"], "round", "#8E4A33",
    n(200, 14, 7, 13, "cooked"), p(150, "3 קציצות", "3 meatballs"), "MG", "mx", "meatballs in tomato sauce"),
  X("kebab", ["protein"], "קבב", "kebab", ["קבב", "קבבים", "kebab", "kabab"], "long", "#8A4630",
    n(250, 17, 3, 19, "cooked"), p(150, "3 קבבים", "3 kebabs"), "M", "mx", "kofta kebab grilled"),
  X("chickenSoup", ["protein", "veg"], "מרק עוף", "chicken soup", ["מרק עוף", "chicken soup"], "drop", "#E8C766",
    n(36, 2.5, 3, 1.5, "cooked"), p(350, "קערה", "1 bowl"), "M", "", "chicken soup bowl"),
  X("vegSoup", ["veg"], "מרק ירקות", "vegetable soup", ["מרק ירקות", "vegetable soup", "veg soup"], "drop", "#D9923E",
    n(35, 1.5, 6, 0.6, "cooked"), p(350, "קערה", "1 bowl"), "", "f", "vegetable soup bowl"),
  X("cholent", ["protein", "carb"], "חמין", "cholent", ["חמין", "צ'ולנט", "צ׳ולנט", "טשולנט", "cholent", "hamin"], "blob", "#7A4A2E",
    n(170, 9, 16, 8, "cooked"), p(300, "צלחת", "1 plate"), "M", "lx", "cholent stew"),
  X("kugel", ["carb"], "קוגל", "kugel", ["קוגל", "קוגל תפוחי אדמה", "קוגל אטריות", "kugel"], "slice", "#C99A4E",
    n(200, 4, 22, 11, "cooked"), p(120, "פרוסה", "1 slice"), "", "p", "potato kugel"),
  X("pizza", ["carb", "dairy"], "פיצה", "pizza", ["פיצה", "משולש פיצה", "פיצות", "pizza", "pizza slice"], "slice", "#E0A04A",
    n(266, 11, 33, 10, "asSold"), p(110, "משולש", "1 slice"), "DG", "px", "pizza slice"),
  X("hamburger", ["protein", "carb"], "המבורגר", "hamburger", ["המבורגר", "המבורגרים", "בורגר", "hamburger", "burger", "cheeseburger"], "round", "#9A5A36",
    n(250, 13, 22, 12, "asSold"), p(220, "המבורגר בלחמנייה", "1 burger in a bun"), "MG", "pxm", "hamburger"),
  X("hotdog", ["protein", "carb"], "נקניקייה בלחמנייה", "hot dog", ["נקניקייה בלחמנייה", "נקניקיה בלחמניה", "hot dog", "hotdog"], "long", "#B8583C",
    n(290, 10.5, 24, 17, "asSold"), p(150, "יחידה", "1 hot dog"), "MG", "pxmy", "hot dog"),
  X("fries", ["carb"], "צ'יפס", "fries", ["צ'יפס", "ציפס", "צ׳יפס", "french fries", "fries", "chips"], "long", "#E8B64A",
    n(312, 3.4, 41, 15, "asSold"), p(150, "מנה בינונית", "a medium portion"), "", "pre", "french fries"),
  X("sushi", ["carb", "protein"], "סושי", "sushi", ["סושי", "מאקי", "sushi", "maki"], "round", "#E8E2D0",
    n(150, 6, 28, 1.5, "asSold"), p(200, "8 יחידות", "8 pieces"), "F", "r", "sushi rolls"),
  X("lasagna", ["carb", "dairy"], "לזניה", "lasagna", ["לזניה", "lasagna", "lasagne"], "slice", "#D2663C",
    n(165, 9, 16, 7, "cooked"), p(300, "ריבוע", "1 square"), "DG", "x", "lasagna"),
  X("bolognese", ["carb", "protein"], "פסטה בולונז", "spaghetti bolognese", ["פסטה בולונז", "ספגטי בולונז", "בולונז", "bolognese", "spaghetti bolognese"], "long", "#B04A30",
    n(150, 8, 18, 5, "cooked"), p(350, "צלחת", "1 plate"), "MG", "rm", "spaghetti bolognese"),
  X("toastCheese", ["carb", "dairy"], "טוסט גבינה", "cheese toastie", ["טוסט", "טוסט גבינה", "טוסט גבינה צהובה", "grilled cheese", "cheese toastie", "toastie"], "slice", "#E3B45A",
    n(300, 13, 30, 14, "asSold"), p(150, "טוסט אחד", "1 toastie"), "DG", "rx", "grilled cheese sandwich"),
  X("sandwich", ["carb", "protein"], "כריך", "sandwich", ["כריך", "כריכים", "סנדוויץ'", "סנדוויץ", "sandwich"], "slice", "#D6A868",
    n(230, 10, 28, 8.5, "asSold"), p(200, "כריך", "1 sandwich"), "G", "r", "sandwich"),
  // -------------------------------------------------- salads & spreads
  X("israeliSalad", ["veg"], "סלט ירקות", "chopped salad", ["סלט ירקות", "סלט ישראלי", "סלט קצוץ", "סלט", "israeli salad", "chopped salad", "salad"], "leaf", "#6FA84A",
    n(60, 1, 4, 4.5, "asSold"), p(200, "קערה", "1 bowl"), "", "f", "israeli salad"),
  X("tabbouleh", ["veg", "carb"], "טאבולה", "tabbouleh", ["טאבולה", "tabbouleh", "tabouli"], "leaf", "#5E9A3C",
    n(120, 2.5, 12, 7, "asSold"), p(150, "קערה קטנה", "a small bowl"), "G", "fo", "tabbouleh"),
  X("matbucha", ["veg"], "מטבוחה", "matbucha", ["מטבוחה", "matbucha"], "blob", "#C2412C",
    n(90, 1.5, 8, 6, "asSold"), p(50, "2 כפות", "2 tbsp"), "", "", "matbucha"),
  X("eggplantSalad", ["veg", "fat"], "סלט חצילים", "eggplant salad", ["סלט חצילים", "חציל במיונז", "באבא גנוש", "baba ganoush", "eggplant salad"], "blob", "#8C6A5A",
    n(130, 2, 7, 10.5, "asSold"), p(60, "2 כפות", "2 tbsp"), "", "", "baba ghanoush"),
  X("coleslaw", ["veg", "fat"], "סלט כרוב", "coleslaw", ["סלט כרוב", "קולסלאו", "coleslaw"], "leaf", "#DDE6C4",
    n(150, 1, 12, 11, "asSold"), p(100, "חצי כוס", "1/2 cup"), "", "p", "coleslaw"),
  X("eggSalad", ["protein", "fat"], "סלט ביצים", "egg salad", ["סלט ביצים", "egg salad"], "blob", "#F2DC8A",
    n(222, 9, 1.5, 20, "asSold"), p(60, "2 כפות גדושות", "2 heaped tbsp"), "", "e", "egg salad"),
  X("potatoSalad", ["carb", "veg"], "סלט תפוחי אדמה", "potato salad", ["סלט תפוחי אדמה", "סלט תפו\"א", "potato salad"], "blob", "#EAD9A0",
    n(145, 2, 14, 9, "asSold"), p(150, "כוס", "1 cup"), "", "p", "potato salad"),
  X("tunaSaladSpread", ["protein", "fat"], "סלט טונה", "tuna mayo", ["סלט טונה במיונז", "טונה במיונז", "tuna mayo"], "blob", "#D6B08A",
    n(190, 15, 3, 13, "asSold"), p(80, "3 כפות", "3 tbsp"), "F", "e", "tuna salad mayonnaise"),
  // ------------------------------------------- more meat, fish, seafood
  X("liver", ["protein"], "כבד עוף", "chicken liver", ["כבד עוף", "כבדי עוף", "כבד", "chicken liver", "liver"], "blob", "#6E2A2A",
    n(159, 24.5, 0.9, 6.5, "cooked"), p(100, "מנה", "1 portion"), "M", "n", "chicken livers dish"),
  X("duck", ["protein"], "ברווז", "duck", ["ברווז", "duck"], "blob", "#9A5238",
    n(195, 23.5, 0, 11.2, "cooked"), p(150, "נתח", "1 portion"), "M", "x", "roast duck"),
  X("veal", ["protein"], "עגל", "veal", ["עגל", "בשר עגל", "veal"], "blob", "#B5705A",
    n(190, 31, 0, 7.5, "cooked"), p(150, "נתח בגודל כף יד", "a palm-sized piece"), "M", "m", "veal steak"),
  X("pastrami", ["protein"], "פסטרמה", "pastrami", ["פסטרמה", "פסטרמה הודו", "pastrami"], "slice", "#B8646A",
    n(137, 21, 3, 4.5, "asSold"), p(50, "4 פרוסות", "4 slices"), "M", "py", "pastrami slices"),
  X("salami", ["protein", "fat"], "סלמי", "salami", ["סלמי", "נקניק סלמי", "salami"], "slice", "#A33A3A",
    n(402, 22, 2, 34, "asSold"), p(30, "כמה פרוסות", "a few slices"), "M", "pxmy", "salami slices"),
  X("bacon", ["protein", "fat"], "בייקון", "bacon", ["בייקון", "bacon"], "long", "#C0584A",
    n(532, 37, 1.4, 42, "cooked"), p(20, "2 רצועות", "2 rashers"), "T", "pxmy", "bacon strips"),
  X("ham", ["protein"], "ג'מבון", "ham", ["ג'מבון", "ג׳מבון", "חזיר מעושן", "ham"], "slice", "#E08C8C",
    n(145, 21, 1.5, 6, "asSold"), p(50, "3 פרוסות", "3 slices"), "T", "pmy", "sliced ham"),
  X("calamari", ["protein"], "קלמרי", "calamari", ["קלמרי", "קלמרים", "דיונון", "calamari", "squid"], "round", "#EDE0C8",
    n(175, 18, 8, 7.5, "cooked"), p(120, "מנה", "1 portion"), "S", "p", "fried calamari"),
  X("crab", ["protein"], "סרטן", "crab", ["סרטן", "סרטנים", "crab"], "blob", "#E4704E",
    n(97, 19, 0, 1.5, "cooked"), p(100, "מנה", "1 portion"), "S", "4", "crab meat dish"),
  X("lobster", ["protein"], "לובסטר", "lobster", ["לובסטר", "lobster"], "long", "#D8503A",
    n(89, 19, 0, 0.9, "cooked"), p(120, "מנה", "1 portion"), "S", "4", "lobster dish"),
  X("mussels", ["protein"], "מולים", "mussels", ["מולים", "צדפות", "פירות ים", "mussels", "seafood", "clams"], "round", "#3E3A4E",
    n(172, 24, 7.4, 4.5, "cooked"), p(120, "קערה קטנה", "a small bowl"), "S", "4", "mussels dish"),
  X("octopus", ["protein"], "תמנון", "octopus", ["תמנון", "octopus"], "long", "#B85A6A",
    n(164, 30, 4.4, 2.1, "cooked"), p(120, "מנה", "1 portion"), "S", "4", "grilled octopus"),
  X("surimi", ["protein"], "סורימי", "surimi", ["סורימי", "מקלות סורימי", "surimi", "crab sticks"], "long", "#F0A08C",
    n(95, 7.6, 15, 0.9, "asSold"), p(80, "4 מקלות", "4 sticks"), "F", "p", "surimi sticks"),
  X("tilapia", ["protein"], "אמנון", "tilapia", ["אמנון", "מושט", "tilapia"], "long", "#D8CDB8",
    n(128, 26, 0, 2.7, "cooked"), p(150, "פילה", "1 fillet"), "F", "n4", "tilapia fillet"),
  X("seaBream", ["protein"], "דניס", "sea bream", ["דניס", "sea bream", "dorade"], "long", "#C8C8C0",
    n(135, 24, 0, 4.3, "cooked"), p(200, "דג שלם קטן", "1 small whole fish"), "F", "n4", "grilled sea bream"),
  X("seaBass", ["protein"], "לברק", "sea bass", ["לברק", "sea bass", "branzino"], "long", "#BFC6C8",
    n(124, 23.6, 0, 2.6, "cooked"), p(200, "דג שלם קטן", "1 small whole fish"), "F", "n4", "grilled sea bass"),
  X("mullet", ["protein"], "בורי", "mullet", ["בורי", "mullet"], "long", "#A8AEB2",
    n(150, 25, 0, 5.5, "cooked"), p(150, "פילה", "1 fillet"), "F", "4", "grilled mullet fish plate"),
  X("cod", ["protein"], "בקלה", "cod", ["בקלה", "cod", "hake", "הייק"], "long", "#EEE6D6",
    n(100, 23, 0, 0.9, "cooked"), p(150, "פילה", "1 fillet"), "F", "n4", "baked cod fillet"),
  X("trout", ["protein"], "פורל", "trout", ["פורל", "trout"], "long", "#C9967A",
    n(162, 24, 0, 7.4, "cooked"), p(150, "פילה", "1 fillet"), "F", "3", "baked trout"),
  X("herring", ["protein", "fat"], "הרינג", "herring", ["הרינג", "דג מלוח", "herring"], "long", "#8C8E96",
    n(212, 17, 0, 16, "asSold"), p(50, "2 חתיכות", "2 pieces"), "F", "3y", "pickled herring"),
  X("smokedSalmon", ["protein"], "סלמון מעושן", "smoked salmon", ["סלמון מעושן", "לקס", "smoked salmon", "lox"], "slice", "#EE8A6E",
    n(117, 18, 0, 4.3, "asSold"), p(50, "3 פרוסות", "3 slices"), "F", "3y", "smoked salmon slices"),
  X("tunaOil", ["protein", "fat"], "טונה בשמן", "tuna in oil", ["טונה בשמן", "tuna in oil"], "blob", "#C08060",
    n(198, 29, 0, 8.2, "drained"), p(100, "קופסה", "1 can"), "F", "4", "canned tuna in oil"),
  X("eggWhite", ["protein"], "חלבון ביצה", "egg whites", ["חלבוני ביצה", "חלבון ביצה", "egg whites", "egg white"], "blob", "#FAFAF6",
    n(52, 10.9, 0.7, 0.2, "raw"), p(100, "3 חלבונים", "3 whites"), "", "n", "egg whites"),
  X("plantBurger", ["protein"], "קציצה צמחונית", "veggie burger", ["קציצה צמחונית", "המבורגר צמחוני", "טבעול", "קציצות טבעול", "veggie burger", "plant burger"], "round", "#8E6A4A",
    n(210, 15, 12, 11, "cooked"), p(100, "קציצה", "1 patty"), "", "p", "veggie burger patty"),
  X("soyProtein", ["protein"], "חלבון סויה", "soy chunks", ["חלבון סויה", "גרגירי סויה", "soy chunks", "tvp"], "grain", "#C8A878",
    n(330, 50, 30, 1, "dry"), p(30, "חופן יבש", "a dry handful"), "", "nl", "textured soy protein"),
  // ----------------------------------------------------------- dairy
  X("sourCream", ["dairy", "fat"], "שמנת חמוצה", "sour cream", ["שמנת חמוצה", "שמנת", "sour cream"], "blob", "#FAF6EA",
    n(198, 2.4, 4.6, 19, "asSold"), p(30, "2 כפות", "2 tbsp"), "D", "x", "sour cream"),
  X("sweetCream", ["dairy", "fat"], "שמנת מתוקה", "cream", ["שמנת מתוקה", "שמנת לבישול", "שמנת להקצפה", "heavy cream", "cooking cream"], "drop", "#FBF8EE",
    n(340, 2.1, 2.8, 36, "asSold"), p(30, "2 כפות", "2 tbsp"), "D", "xe", "whipping cream"),
  X("ricotta", ["dairy", "protein"], "ריקוטה", "ricotta", ["ריקוטה", "ricotta"], "blob", "#FBF8F0",
    n(174, 11.3, 3, 13, "asSold"), p(60, "2 כפות גדושות", "2 heaped tbsp"), "D", "x", "ricotta cheese"),
  X("parmesan", ["dairy", "protein", "fat"], "פרמזן", "parmesan", ["פרמזן", "parmesan", "parmigiano"], "grain", "#F0DCA0",
    n(429, 38, 4, 29, "asSold"), p(10, "כף מגוררת", "1 tbsp grated"), "D", "xy", "parmesan cheese"),
  X("goatCheese", ["dairy", "protein", "fat"], "גבינת עזים", "goat cheese", ["גבינת עזים", "גבינת עיזים", "goat cheese"], "blob", "#FAF7EE",
    n(358, 22, 0, 30, "asSold"), p(30, "פרוסה עבה", "a thick slice"), "D", "xy", "goat cheese"),
  X("halloumi", ["dairy", "protein", "fat"], "חלומי", "halloumi", ["חלומי", "halloumi"], "slice", "#F4E8C4",
    n(317, 21, 2, 25, "asSold"), p(50, "2 פרוסות", "2 slices"), "D", "xy", "grilled halloumi"),
  X("tzfatit", ["dairy", "protein", "fat"], "גבינה צפתית", "tzfatit cheese", ["גבינה צפתית", "צפתית", "tzfatit"], "blob", "#FAF6EC",
    n(249, 17, 1.5, 19.5, "asSold"), p(50, "פרוסה", "1 slice"), "D", "xy", "white brined cheese"),
  X("milky", ["dairy", "sweet"], "מילקי", "chocolate pudding", ["מילקי", "מעדן", "מעדן שוקולד", "פודינג", "pudding"], "blob", "#7A4A30",
    n(150, 3, 20, 6.5, "asSold"), p(100, "גביע", "1 pot"), "D", "sp", "chocolate pudding cup"),
  X("proteinYogurt", ["dairy", "protein"], "יוגורט חלבון", "protein yogurt", ["יוגורט חלבון", "יוגורט פרו", "דנונה פרו", "יופלה גו", "protein yogurt"], "blob", "#F4F0E6",
    n(65, 10, 4.5, 0.8, "asSold"), p(200, "גביע", "1 pot"), "D", "nk", "yogurt cup spoon"),
  X("proteinPudding", ["dairy", "protein"], "מעדן חלבון", "protein pudding", ["מעדן חלבון", "פודינג חלבון", "protein pudding"], "blob", "#8A5A3A",
    n(90, 10, 9, 1.5, "asSold"), p(150, "גביע", "1 pot"), "D", "n", "chocolate pudding"),
  X("leben", ["dairy"], "לבן", "leben", ["אשל", "leben", "buttermilk"], "drop", "#F6F4EE",
    n(58, 3.3, 4.5, 3, "asSold"), p(200, "גביע", "1 pot"), "D", "k", "buttermilk glass"),
  X("iceCream", ["sweet", "dairy"], "גלידה", "ice cream", ["גלידה", "גלידות", "ארטיק", "ice cream"], "round", "#F3D9C2",
    n(209, 3.5, 24, 11, "asSold"), p(100, "2 כדורים", "2 scoops"), "D", "sxe", "ice cream cone"),
  X("chocolateMilk", ["drink", "dairy"], "שוקו", "chocolate milk", ["שוקו", "חלב שוקו", "chocolate milk"], "drop", "#8C5A3C",
    n(81, 3.2, 11.5, 2.5, "asSold"), p(250, "כוס", "1 glass"), "D", "s", "chocolate milk glass"),
  X("proteinBar", ["protein", "sweet"], "חטיף חלבון", "protein bar", ["חטיף חלבון", "חטיפי חלבון", "protein bar"], "long", "#6E4A34",
    n(368, 30, 35, 12, "asSold"), p(60, "חטיף", "1 bar"), "D", "p", "protein bar"),
  // -------------------------------------------------- bakery & starches
  X("lafa", ["carb"], "לאפה", "laffa", ["לאפה", "לאפות", "laffa", "lafa"], "round", "#E4C990",
    n(270, 9, 55, 1.5, "asSold"), p(110, "לאפה אחת", "1 laffa"), "G", "r", "laffa flatbread"),
  X("croissant", ["carb", "fat"], "קרואסון", "croissant", ["קרואסון", "קרואסונים", "croissant"], "long", "#D9A04E",
    n(406, 8.2, 45.8, 21, "asSold"), p(60, "יחידה", "1 croissant"), "DG", "rxe", "croissant"),
  X("pancakes", ["carb"], "פנקייק", "pancakes", ["פנקייק", "פנקייקים", "חביתיות", "pancakes", "crepes"], "round", "#E0B060",
    n(227, 6.4, 28, 10, "cooked"), p(120, "3 פנקייקים", "3 pancakes"), "DG", "r", "pancakes stack"),
  X("matza", ["carb"], "מצה", "matzah", ["מצה", "מצות", "matzah", "matzo"], "slice", "#E8D2A0",
    n(390, 10, 84, 1.5, "asSold"), p(30, "מצה אחת", "1 sheet"), "G", "r", "matzah"),
  X("crackers", ["carb"], "קרקרים", "crackers", ["קרקרים", "קרקר", "crackers"], "slice", "#DDB870",
    n(430, 9, 68, 13.5, "asSold"), p(30, "6 קרקרים", "6 crackers"), "G", "ry", "crackers snack"),
  X("flour", ["carb"], "קמח", "flour", ["קמח", "קמח לבן", "קמח מלא", "flour"], "grain", "#F6F1E4",
    n(364, 10.3, 76.3, 1, "dry"), p(30, "רבע כוס", "1/4 cup"), "G", "r", "flour bowl"),
  X("semolina", ["carb"], "סולת", "semolina", ["סולת", "semolina"], "grain", "#F0DC9C",
    n(360, 12.7, 72.8, 1, "dry"), p(30, "3 כפות", "3 tbsp"), "G", "r", "semolina"),
  X("breadcrumbs", ["carb"], "פירורי לחם", "breadcrumbs", ["פירורי לחם", "פירורי פנקו", "פנקו", "breadcrumbs", "panko"], "grain", "#D8B070",
    n(395, 13, 72, 5.3, "dry"), p(20, "2 כפות", "2 tbsp"), "G", "r", "breadcrumbs"),
  X("cookedRice", ["carb"], "אורז מבושל", "cooked rice", ["אורז מבושל", "אורז לבן מבושל", "cooked rice"], "grain", "#F4F0E2",
    n(130, 2.7, 28, 0.3, "cooked"), p(150, "כוס מבושל", "1 cup cooked"), "", "r", "bowl of cooked rice"),
  X("cookedPasta", ["carb"], "פסטה מבושלת", "cooked pasta", ["פסטה מבושלת", "cooked pasta"], "long", "#EEDDA0",
    n(158, 5.8, 31, 0.9, "cooked"), p(200, "צלחת", "1 plate"), "G", "r", "cooked pasta plate"),
  X("mashedPotato", ["carb", "veg"], "פירה", "mashed potato", ["פירה", "פירה תפוחי אדמה", "mashed potatoes", "mash"], "blob", "#F0E2B0",
    n(88, 2, 15, 2.5, "cooked"), p(200, "כוס", "1 cup"), "", "", "mashed potatoes"),
  X("popcorn", ["carb"], "פופקורן", "popcorn", ["פופקורן", "popcorn"], "grain", "#F6E8B8",
    n(387, 13, 78, 4.5, "asSold"), p(25, "קערה", "1 bowl"), "", "w", "popcorn bowl"),
  X("granolaBar", ["carb", "sweet"], "חטיף דגנים", "granola bar", ["חטיף דגנים", "חטיף גרנולה", "חטיף אנרגיה", "granola bar", "cereal bar"], "long", "#B88A4A",
    n(437, 7, 64, 17, "asSold"), p(30, "חטיף", "1 bar"), "G", "s", "granola bar"),
  // ------------------------------------------------ snacks & sweets
  X("bamba", ["sweet", "fat"], "במבה", "bamba", ["במבה", "bamba"], "long", "#E8B040",
    n(534, 15, 38, 35, "asSold"), p(25, "שקית קטנה", "1 small bag"), "", "pe", "bamba peanut snack"),
  X("bisli", ["sweet", "carb"], "ביסלי", "bissli", ["ביסלי", "bissli"], "grain", "#D89A3A",
    n(480, 9, 64, 20.5, "asSold"), p(35, "שקית קטנה", "1 small bag"), "G", "pye", "bissli snack"),
  X("potatoChips", ["sweet", "fat"], "תפוצ'יפס", "potato chips", ["תפוצ'יפס", "תפוציפס", "צ'יפס שקית", "potato chips", "crisps"], "round", "#EACB6A",
    n(536, 7, 53, 35, "asSold"), p(30, "שקית קטנה", "1 small bag"), "", "pye", "potato chips"),
  X("pretzels", ["sweet", "carb"], "בייגלה", "pretzels", ["בייגלה", "בייגלה מלוח", "pretzels", "pretzel"], "long", "#B87A3A",
    n(380, 10, 80, 3, "asSold"), p(30, "חופן", "a handful"), "G", "ry", "pretzel sticks"),
  X("cake", ["sweet", "carb"], "עוגה", "cake", ["עוגה", "עוגות", "עוגת שוקולד", "עוגת גבינה", "עוגת שמרים", "cake"], "slice", "#9A6A4A",
    n(373, 5, 50, 17, "asSold"), p(80, "פרוסה", "1 slice"), "G", "sxe", "slice of cake"),
  X("cookies", ["sweet", "carb"], "עוגיות", "cookies", ["עוגיות", "עוגייה", "עוגיה", "ביסקוויטים", "cookies", "biscuits"], "round", "#C8904E",
    n(480, 5.5, 64, 22.5, "asSold"), p(30, "3 עוגיות", "3 cookies"), "G", "sxe", "cookies plate"),
  X("donut", ["sweet", "carb"], "סופגנייה", "doughnut", ["סופגנייה", "סופגניה", "סופגניות", "דונאט", "דונאטס", "donut", "doughnut"], "round", "#D88A4A",
    n(421, 5, 50, 22.5, "asSold"), p(70, "יחידה", "1 doughnut"), "G", "spxe", "glazed donuts"),
  X("rugelach", ["sweet", "carb"], "רוגלך", "rugelach", ["רוגלך", "רוגעלך", "rugelach"], "long", "#8E5A34",
    n(433, 6, 55, 21, "asSold"), p(40, "2 יחידות", "2 pieces"), "G", "sxe", "rugelach"),
  X("wafers", ["sweet", "carb"], "ופלים", "wafers", ["ופלים", "ופל", "wafers", "wafer"], "slice", "#E0B070",
    n(501, 6, 63, 25, "asSold"), p(25, "3 ופלים", "3 wafers"), "G", "spe", "wafer biscuits"),
  X("krembo", ["sweet"], "קרמבו", "krembo", ["קרמבו", "krembo"], "round", "#6A3A2A",
    n(400, 4, 60, 16, "asSold"), p(25, "יחידה", "1 krembo"), "DG", "sp", "chocolate coated marshmallow"),
  X("milkChocolate", ["sweet", "fat"], "שוקולד חלב", "milk chocolate", ["שוקולד חלב", "שוקולד", "טבלת שוקולד", "milk chocolate", "chocolate"], "slice", "#7A4A30",
    n(535, 7.7, 59.4, 29.7, "asSold"), p(25, "4 קוביות", "4 squares"), "D", "sxe", "milk chocolate bar"),
  X("candy", ["sweet"], "סוכריות", "candy", ["סוכריות", "סוכריה", "ממתקים", "גומי", "candy", "sweets", "gummies"], "round", "#E24A7A",
    n(394, 0, 98, 0.2, "asSold"), p(20, "חופן קטן", "a small handful"), "", "sp", "gummy candies"),
  X("halva", ["sweet", "fat"], "חלבה", "halva", ["חלבה", "halva", "halwa"], "slice", "#D8C090",
    n(481, 12, 60, 21.5, "asSold"), p(30, "קובייה", "1 piece"), "", "se", "halva"),
  X("nutella", ["sweet", "fat"], "ממרח שוקולד", "chocolate spread", ["ממרח שוקולד", "נוטלה", "nutella", "chocolate spread"], "blob", "#5E3622",
    n(533, 6.3, 57.5, 30.9, "asSold"), p(20, "כף", "1 tbsp"), "D", "sxe", "nutella jar"),
  X("jam", ["sweet"], "ריבה", "jam", ["ריבה", "ריבת תות", "jam", "jelly"], "blob", "#B02A3A",
    n(254, 0.4, 63, 0.1, "asSold"), p(20, "כף", "1 tbsp"), "", "s", "jar of jam"),
  X("sugar", ["sweet"], "סוכר", "sugar", ["סוכר", "סוכר חום", "sugar"], "grain", "#F8F6F0",
    n(387, 0, 100, 0, "asSold"), p(5, "כפית", "1 tsp"), "", "s", "granulated sugar"),
  X("silan", ["sweet"], "סילאן", "date syrup", ["סילאן", "silan", "date syrup"], "drop", "#5A2E1E",
    n(284, 1, 70, 0, "asSold"), p(15, "כף", "1 tbsp"), "", "s", "date molasses"),
  // ---------------------------------------------------------- produce
  X("mint", ["veg"], "נענע", "mint", ["נענע", "מנטה", "mint"], "leaf", "#4E9A4A",
    n(53, 3.3, 8.4, 0.7, "raw"), p(5, "כמה עלים", "a few leaves"), "", "", "fresh mint leaves"),
  X("basil", ["veg"], "בזיליקום", "basil", ["בזיליקום", "ריחן", "basil"], "leaf", "#3E8A3A",
    n(23, 3.2, 1.2, 0.6, "raw"), p(5, "כמה עלים", "a few leaves"), "", "", "basil leaves"),
  X("dill", ["veg"], "שמיר", "dill", ["שמיר", "dill"], "leaf", "#6AA04A",
    n(43, 3.5, 5, 1.1, "raw"), p(5, "חופן קצוץ", "a small handful"), "", "", "fresh dill"),
  X("ginger", ["veg"], "ג'ינג'ר", "ginger", ["ג'ינג'ר", "ג׳ינג׳ר", "גינגר", "זנגביל", "ginger"], "long", "#D8B46A",
    n(80, 1.8, 16, 0.8, "raw"), p(5, "פרוסה", "1 slice"), "", "", "ginger rhizome"),
  X("chili", ["veg"], "פלפל חריף", "chili", ["פלפל חריף", "צ'ילי", "צ׳ילי", "חלפיניו", "chili", "jalapeno"], "long", "#D62A2A",
    n(40, 1.9, 7.3, 0.4, "raw"), p(15, "יחידה", "1 chili"), "", "", "red chilli peppers"),
  X("greenOnion", ["veg"], "בצל ירוק", "spring onion", ["בצל ירוק", "spring onion", "scallion", "green onion"], "long", "#7AB85A",
    n(32, 1.8, 4.7, 0.2, "raw"), p(15, "גבעול", "1 stalk"), "", "", "spring onions"),
  X("okra", ["veg"], "במיה", "okra", ["במיה", "okra"], "long", "#6E9A3E",
    n(33, 1.9, 4.3, 0.2, "raw"), p(100, "חופן", "a handful"), "", "f", "okra"),
  X("fennel", ["veg"], "שומר", "fennel", ["שומר", "fennel"], "round", "#C8D8A0",
    n(31, 1.2, 4.2, 0.2, "raw"), p(100, "חצי פקעת", "1/2 bulb"), "", "f", "fennel bulb"),
  X("pickles", ["veg"], "מלפפון חמוץ", "pickles", ["מלפפון חמוץ", "מלפפונים חמוצים", "חמוצים", "pickles", "pickle"], "long", "#7E8E3A",
    n(12, 0.3, 2.3, 0.2, "drained"), p(60, "2 מלפפונים", "2 pickles"), "", "yk", "pickled cucumbers"),
  X("tomatoSauce", ["veg"], "רוטב עגבניות", "tomato sauce", ["רוטב עגבניות", "רסק עגבניות", "רסק", "פסטה רוסו", "passata", "tomato sauce", "tomato paste"], "drop", "#C8382A",
    n(33, 1.3, 5.5, 0.2, "asSold"), p(60, "רבע כוס", "1/4 cup"), "", "", "tomato sauce bowl"),
  X("melon", ["fruit"], "מלון", "melon", ["מלון", "melon", "cantaloupe"], "round", "#F2B46A",
    n(34, 0.8, 8.2, 0.2, "raw"), p(200, "פלח", "1 wedge"), "", "", "cantaloupe melon"),
  X("papaya", ["fruit"], "פפאיה", "papaya", ["פפאיה", "פאפיה", "papaya"], "round", "#F0904A",
    n(43, 0.5, 9, 0.3, "raw"), p(150, "חצי", "1/2 fruit"), "", "", "papaya fruit cut"),
  X("lychee", ["fruit"], "ליצ'י", "lychee", ["ליצ'י", "ליצ׳י", "ליצי", "lychee", "litchi"], "round", "#E8A0A8",
    n(66, 0.8, 15, 0.4, "raw"), p(100, "10 יחידות", "10 fruits"), "", "", "lychee fruit"),
  X("coconut", ["fat", "fruit"], "קוקוס", "coconut", ["קוקוס", "קוקוס טחון", "coconut"], "round", "#F4F0E4",
    n(354, 3.3, 15, 33.5, "asSold"), p(20, "2 כפות", "2 tbsp"), "", "xe", "coconut"),
  X("guava", ["fruit"], "גויאבה", "guava", ["גויאבה", "גויאבות", "guava"], "round", "#C8D86A",
    n(68, 2.6, 9, 1, "raw"), p(100, "יחידה", "1 guava"), "", "f", "guava fruit"),
  X("nectarine", ["fruit"], "נקטרינה", "nectarine", ["נקטרינה", "נקטרינות", "nectarine"], "round", "#E86A4A",
    n(44, 1.1, 8.9, 0.3, "raw"), p(140, "יחידה", "1 nectarine"), "", "", "nectarines"),
  X("passionfruit", ["fruit"], "פסיפלורה", "passion fruit", ["פסיפלורה", "passion fruit"], "round", "#6A3A6A",
    n(97, 2.2, 20, 0.7, "raw"), p(20, "יחידה", "1 fruit"), "", "f", "passion fruit"),
  X("raisins", ["fruit"], "צימוקים", "raisins", ["צימוקים", "raisins"], "grain", "#4E2A3A",
    n(299, 3.1, 75, 0.5, "asSold"), p(30, "חופן קטן", "a small handful"), "", "e", "raisins"),
  X("driedFruit", ["fruit"], "פירות יבשים", "dried fruit", ["פירות יבשים", "פירות מיובשים", "משמש מיובש", "משמשים מיובשים", "dried fruit", "dried apricots"], "round", "#E09040",
    n(241, 3.4, 58, 0.5, "asSold"), p(30, "חופן קטן", "a small handful"), "", "e", "dried apricots"),
  X("prunes", ["fruit"], "שזיפים מיובשים", "prunes", ["שזיפים מיובשים", "שזיף מיובש", "prunes"], "round", "#3E2230",
    n(240, 2.2, 57, 0.4, "asSold"), p(30, "4 יחידות", "4 prunes"), "", "fe", "prunes dried plums"),
  X("cranberries", ["fruit"], "חמוציות", "dried cranberries", ["חמוציות", "cranberries"], "round", "#A8243A",
    n(308, 0.2, 75, 1.1, "asSold"), p(30, "חופן קטן", "a small handful"), "", "se", "dried cranberries"),
  X("lime", ["fruit"], "ליים", "lime", ["ליים", "לימון ירוק", "lime"], "round", "#8AB83A",
    n(30, 0.7, 7.7, 0.2, "raw"), p(20, "סחיטה", "a squeeze"), "", "", "limes"),
  X("fruitSalad", ["fruit"], "סלט פירות", "fruit salad", ["סלט פירות", "fruit salad"], "round", "#E8704A",
    n(50, 0.6, 12.5, 0.2, "raw"), p(200, "קערה", "1 bowl"), "", "f", "fruit salad bowl"),
  // ------------------------------------------------ nuts, seeds, spreads
  X("cashews", ["fat", "protein"], "קשיו", "cashews", ["קשיו", "אגוזי קשיו", "cashews", "cashew"], "grain", "#E8D0A0",
    n(553, 18.2, 30.2, 43.9, "asSold"), p(25, "חופן", "a handful"), "", "oe", "roasted cashew nuts"),
  X("pistachios", ["fat", "protein"], "פיסטוק", "pistachios", ["פיסטוק", "פיסטוקים", "pistachios", "pistachio"], "grain", "#9AB060",
    n(560, 20.2, 27.2, 45.3, "asSold"), p(25, "חופן", "a handful"), "", "oe", "pistachio nuts"),
  X("peanuts", ["fat", "protein"], "בוטנים", "peanuts", ["בוטנים", "בוטן", "peanuts"], "grain", "#C8945A",
    n(567, 25.8, 16.1, 49.2, "asSold"), p(25, "חופן", "a handful"), "", "oe", "peanuts"),
  X("hazelnuts", ["fat", "protein"], "אגוזי לוז", "hazelnuts", ["אגוזי לוז", "לוז", "hazelnuts"], "grain", "#A0703E",
    n(628, 15, 16.7, 60.8, "asSold"), p(25, "חופן", "a handful"), "", "oe", "hazelnuts"),
  X("pecans", ["fat", "protein"], "פקאן", "pecans", ["פקאן", "אגוזי פקאן", "pecans"], "grain", "#8A5A34",
    n(691, 9.2, 13.9, 72, "asSold"), p(25, "חופן", "a handful"), "", "oe", "pecan nuts"),
  X("sesame", ["fat", "protein"], "שומשום", "sesame seeds", ["שומשום", "sesame"], "grain", "#EEE0B8",
    n(573, 17.7, 23.4, 49.7, "asSold"), p(10, "כף", "1 tbsp"), "", "o", "sesame seeds bowl"),
  X("almondButter", ["fat", "protein"], "חמאת שקדים", "almond butter", ["חמאת שקדים", "almond butter"], "blob", "#B88A5A",
    n(614, 21, 18.8, 55.5, "asSold"), p(20, "כף", "1 tbsp"), "", "oe", "almond butter jar"),
  X("margarine", ["fat"], "מרגרינה", "margarine", ["מרגרינה", "margarine"], "blob", "#F4E08A",
    n(717, 0.2, 0.7, 80, "asSold"), p(10, "כפית", "1 tsp"), "", "pe", "margarine"),
  X("canolaOil", ["fat"], "שמן", "oil", ["שמן קנולה", "שמן צמחי", "שמן חמניות", "שמן", "canola oil", "vegetable oil", "oil"], "drop", "#E8D060",
    n(884, 0, 0, 100, "asSold"), p(10, "כף", "1 tbsp"), "", "e", "bottle of vegetable oil"),
  X("coconutOil", ["fat"], "שמן קוקוס", "coconut oil", ["שמן קוקוס", "coconut oil"], "blob", "#F6F2E8",
    n(862, 0, 0, 100, "asSold"), p(10, "כף", "1 tbsp"), "", "xe", "coconut oil jar"),
  // ------------------------------------------- seasonings & condiments
  X("salt", ["spice"], "מלח", "salt", ["מלח", "מלח גס", "salt"], "grain", "#F4F4F4",
    n(0, 0, 0, 0, "asSold"), p(1, "קורט", "a pinch"), "", "y", "salt crystals"),
  X("blackPepper", ["spice"], "פלפל שחור", "black pepper", ["פלפל שחור", "פלפל גרוס", "black pepper"], "grain", "#3A3A3A",
    n(251, 10, 38.7, 3.3, "asSold"), p(1, "קורט", "a pinch"), "", "", "black peppercorns"),
  X("cumin", ["spice"], "כמון", "cumin", ["כמון", "cumin"], "grain", "#A8743A",
    n(375, 17.8, 33.7, 22.3, "asSold"), p(2, "כפית", "1 tsp"), "", "", "ground cumin"),
  X("paprika", ["spice"], "פפריקה", "paprika", ["פפריקה", "paprika"], "grain", "#C8402A",
    n(282, 14, 19.9, 13, "asSold"), p(2, "כפית", "1 tsp"), "", "", "paprika powder"),
  X("turmeric", ["spice"], "כורכום", "turmeric", ["כורכום", "turmeric"], "grain", "#E8A020",
    n(312, 9.7, 51, 3.3, "asSold"), p(2, "כפית", "1 tsp"), "", "", "turmeric powder"),
  X("cinnamon", ["spice"], "קינמון", "cinnamon", ["קינמון", "cinnamon"], "grain", "#9A5A2A",
    n(140, 4, 27.5, 1.2, "asSold"), p(2, "כפית", "1 tsp"), "", "", "cinnamon sticks"),
  X("zaatar", ["spice"], "זעתר", "za'atar", ["זעתר", "זעטר", "zaatar", "za'atar"], "grain", "#7A8A3A",
    n(300, 9, 30, 16, "asSold"), p(3, "כפית", "1 tsp"), "", "", "zaatar spice"),
  X("baharat", ["spice"], "בהרט", "baharat", ["בהרט", "ראס אל חנות", "baharat", "spice mix"], "grain", "#8A4A2A",
    n(290, 10, 40, 10, "asSold"), p(2, "כפית", "1 tsp"), "", "", "spice market"),
  X("soupPowder", ["spice"], "אבקת מרק", "stock powder", ["אבקת מרק", "stock powder", "bouillon"], "grain", "#E8C44A",
    n(252, 10, 35, 8, "asSold"), p(5, "כפית", "1 tsp"), "", "py", "soup powder"),
  X("soySauce", ["spice"], "רוטב סויה", "soy sauce", ["רוטב סויה", "סויה", "soy sauce"], "drop", "#3A2218",
    n(53, 8.1, 4.9, 0.6, "asSold"), p(15, "כף", "1 tbsp"), "G", "y", "soy sauce"),
  X("mustard", ["spice"], "חרדל", "mustard", ["חרדל", "mustard"], "blob", "#D8A820",
    n(60, 3.7, 5.3, 3.3, "asSold"), p(10, "כפית", "1 tsp"), "", "", "mustard jar"),
  X("schug", ["spice"], "סחוג", "schug", ["סחוג", "סחוק", "schug", "zhug"], "blob", "#4A7A2A",
    n(100, 2, 6, 7.5, "asSold"), p(10, "כפית", "1 tsp"), "", "", "zhug hot sauce"),
  X("amba", ["spice"], "עמבה", "amba", ["עמבה", "amba"], "blob", "#D89A2A",
    n(60, 0.5, 12, 1, "asSold"), p(15, "כף", "1 tbsp"), "", "sy", "mango pickle"),
  X("pesto", ["spice", "fat"], "פסטו", "pesto", ["פסטו", "pesto"], "blob", "#4E8A3A",
    n(449, 5, 6, 45, "asSold"), p(15, "כף", "1 tbsp"), "D", "e", "pesto sauce"),
  X("vinegar", ["spice"], "חומץ", "vinegar", ["חומץ", "חומץ בלסמי", "חומץ תפוחים", "vinegar", "balsamic"], "drop", "#6A2A2A",
    n(20, 0, 5, 0, "asSold"), p(15, "כף", "1 tbsp"), "", "", "balsamic vinegar"),
  // ----------------------------------------------------------- drinks
  X("coffee", ["drink"], "קפה", "coffee", ["קפה", "קפה שחור", "אספרסו", "נס קפה", "coffee", "espresso", "americano"], "drop", "#4A2E20",
    n(2, 0.1, 0, 0, "asSold"), p(240, "כוס", "1 cup"), "", "", "cup of coffee"),
  X("latte", ["drink", "dairy"], "קפה הפוך", "latte", ["קפה הפוך", "הפוך", "קפוצ'ינו", "קפוצינו", "לאטה", "latte", "cappuccino"], "drop", "#C8A078",
    n(54, 3.2, 4.8, 2.5, "asSold"), p(250, "כוס", "1 cup"), "D", "", "cappuccino cup"),
  X("tea", ["drink"], "תה", "tea", ["תה", "תה ירוק", "tea", "green tea"], "drop", "#B8702A",
    n(1, 0, 0.2, 0, "asSold"), p(250, "כוס", "1 cup"), "", "", "cup of tea"),
  X("cola", ["drink"], "קולה", "cola", ["קולה", "קוקה קולה", "פפסי", "משקה מוגז", "cola", "coke", "soda", "soft drink"], "drop", "#3A1A12",
    n(42, 0, 10.6, 0, "asSold"), p(330, "פחית", "1 can"), "", "sp", "glass of cola"),
  X("dietCola", ["drink"], "קולה זירו", "diet cola", ["קולה זירו", "קולה דיאט", "דיאט קולה", "זירו", "diet coke", "coke zero", "diet cola"], "drop", "#2A1A14",
    n(0.3, 0.1, 0, 0, "asSold"), p(330, "פחית", "1 can"), "", "p", "can of diet cola"),
  X("orangeJuice", ["drink", "fruit"], "מיץ תפוזים", "orange juice", ["מיץ תפוזים", "תפוזים סחוט", "orange juice"], "drop", "#F4A020",
    n(45, 0.7, 10.4, 0.2, "asSold"), p(250, "כוס", "1 glass"), "", "s", "glass of orange juice"),
  X("juice", ["drink", "fruit"], "מיץ", "juice", ["מיץ", "מיץ תפוחים", "מיץ ענבים", "juice", "apple juice"], "drop", "#E8B040",
    n(46, 0.3, 11, 0.1, "asSold"), p(250, "כוס", "1 glass"), "", "s", "glass of apple juice"),
  X("smoothie", ["drink", "fruit"], "שייק פירות", "smoothie", ["שייק פירות", "שייק", "סמותי", "smoothie"], "drop", "#D8506A",
    n(55, 0.7, 13, 0.3, "asSold"), p(300, "כוס", "1 glass"), "", "", "fruit smoothie"),
  X("lemonade", ["drink"], "לימונדה", "lemonade", ["לימונדה", "לימונענע", "lemonade"], "drop", "#F2E06A",
    n(40, 0, 10, 0, "asSold"), p(300, "כוס", "1 glass"), "", "s", "glass of lemonade"),
  X("energyDrink", ["drink"], "משקה אנרגיה", "energy drink", ["משקה אנרגיה", "רד בול", "red bull", "energy drink"], "drop", "#3A6ABA",
    n(45, 0, 11, 0, "asSold"), p(250, "פחית", "1 can"), "", "sp", "energy drink can"),
  X("soyMilk", ["drink", "protein"], "חלב סויה", "soy milk", ["חלב סויה", "משקה סויה", "soy milk"], "drop", "#F4EEDC",
    n(54, 3.3, 6, 1.8, "asSold"), p(200, "כוס", "1 cup"), "", "", "soy milk carton"),
  X("almondMilk", ["drink"], "חלב שקדים", "almond milk", ["חלב שקדים", "משקה שקדים", "almond milk"], "drop", "#F2EADC",
    n(17, 0.6, 0.6, 1.3, "asSold"), p(200, "כוס", "1 cup"), "", "", "glass of almond milk"),
  X("oatMilk", ["drink"], "חלב שיבולת שועל", "oat milk", ["חלב שיבולת שועל", "משקה שיבולת שועל", "oat milk"], "drop", "#EFE4CC",
    n(46, 1, 6.7, 1.5, "asSold"), p(200, "כוס", "1 cup"), "G", "", "oat milk"),
  X("beer", ["drink"], "בירה", "beer", ["בירה", "בירות", "beer"], "drop", "#E0A62A",
    n(43, 0.5, 3.6, 0, "asSold", 3.9), p(330, "בקבוק", "1 bottle"), "G", "se", "glass of beer"),
  X("wine", ["drink"], "יין", "wine", ["יין", "יין אדום", "יין לבן", "wine", "red wine", "white wine"], "drop", "#7A1A2E",
    n(83, 0.1, 2.6, 0, "asSold", 10.6), p(150, "כוס", "1 glass"), "", "e", "glass of red wine"),
  X("spirits", ["drink"], "משקה חריף", "spirits", ["ערק", "וודקה", "ויסקי", "משקה חריף", "vodka", "whisky", "arak"], "drop", "#E8EEF2",
    n(231, 0, 0, 0, "asSold", 33), p(40, "צ'ייסר", "1 shot"), "", "se", "shot glass"),
];

/**
 * The phrase each ORIGINAL library food's photograph is found by. Commons is
 * catalogued in English and by what is in the frame, so "pepper" alone brings
 * back black pepper and "orange" a colour swatch — these say what to show.
 */
export const BASE_FOOD_PHOTO: Record<string, string> = {
  egg: "eggs", chicken: "grilled chicken breast", turkey: "sliced turkey breast", beef: "beef steak",
  tuna: "canned tuna", salmon: "salmon fillet", fish: "white fish fillet", tofu: "tofu",
  lentils: "lentils", chickpeas: "chickpeas", beans: "cannellini beans", edamame: "edamame",
  cottage: "cottage cheese bowl", whiteCheese: "fromage frais", greekYogurt: "yogurt in a bowl", yellowCheese: "cheese slices plate",
  feta: "feta cheese", milk: "pouring milk glass", wholeBread: "rye bread slices", bread: "bread rolls basket",
  oats: "rolled oats", rice: "white rice", pasta: "pasta", potato: "potatoes vegetable", sweetPotato: "sweet potatoes",
  quinoa: "cooked quinoa", couscous: "couscous", tortilla: "tortilla wraps", corn: "corn on the cob cooked",
  tomato: "tomatoes", cucumber: "cucumbers", lettuce: "lettuce", pepper: "bell pepper vegetable", onion: "red onions",
  garlic: "garlic bulbs", spinach: "spinach leaves", carrot: "carrots", broccoli: "broccoli", cauliflower: "cauliflower",
  zucchini: "zucchini", mushroom: "mushrooms", eggplant: "aubergine vegetable", avocado: "avocado", sweetcornSalad: "mixed salad greens bowl",
  banana: "bananas", apple: "apples", berries: "blueberries", orange: "oranges fruit", lemon: "lemons",
  dates: "medjool dates fruit", oliveOil: "olive oil", tahini: "tahini", nuts: "mixed nuts", peanutButter: "peanut butter",
  olives: "bowl of olives", hummusSpread: "hummus plate", pork: "pork chop", lamb: "lamb chops grilled", sausage: "sausages on a plate",
  shrimp: "shrimp", sardines: "sardines", proteinPowder: "protein powder", butter: "butter", mozzarella: "mozzarella",
  creamCheese: "cream cheese spread", bagel: "bagels", noodles: "noodles", bulgur: "bulgur", cornflakes: "cornflakes",
  granola: "granola", riceCakes: "rice cakes snack", cabbage: "cabbage", peas: "green peas bowl", greenBeans: "green beans",
  beetroot: "beetroot", celery: "celery stalks", cornVeg: "sweetcorn kernels bowl", grapes: "grapes", mango: "mango",
  watermelon: "watermelon slice", pear: "pears fruit", pineapple: "pineapple fruit", pomegranate: "pomegranate", honey: "honey",
  darkChocolate: "dark chocolate", mayo: "mayonnaise", ketchup: "ketchup", chia: "chia seeds spoon",
  freekeh: "freekeh", barley: "pearl barley", buckwheat: "buckwheat groats", brownRice: "brown rice", millet: "millet grains",
  pitaWhole: "pita", pita: "pita bread", blackBeans: "black beans", fava: "fava beans cooked", tempeh: "tempeh",
  labneh: "labneh", kefir: "kefir", skyr: "skyr", mackerel: "mackerel", kale: "kale leaves vegetable", arugula: "rocket salad leaves",
  chard: "swiss chard", brusselsSprouts: "brussels sprouts", kohlrabi: "kohlrabi", radish: "radishes",
  asparagus: "asparagus", pumpkin: "pumpkins", artichoke: "globe artichoke", leek: "leeks vegetable", parsley: "parsley",
  cilantro: "coriander leaves", kimchi: "kimchi", strawberries: "strawberries fruit", kiwi: "kiwifruit",
  clementine: "clementines", grapefruit: "grapefruit", peach: "peaches", apricot: "apricots", plum: "plums",
  fig: "figs fruit cut", persimmon: "persimmon", cherries: "cherries", almonds: "almonds", walnuts: "shelled walnuts",
  pumpkinSeeds: "pumpkin seeds", sunflowerSeeds: "sunflower seeds snack", flaxseed: "flax seeds linseed",
};

/** How the "can I eat this?" score reads the original foods it has no set
 * entry for yet — the new ones say it in their own row. */
export const SCORE_LETTERS: Record<string, string> = {
  p: "processed", s: "addedSugar", r: "refined", w: "wholegrain", l: "legume", o: "goodFat",
  n: "leanProtein", x: "satFat", m: "redMeat", y: "salty", e: "energyDense", k: "fermented",
  f: "fibre", "3": "oilyFish", "4": "lightFish",
};
