// Generated by scripts/bundle-meal-photos.mjs — do not edit by hand.
// Real photographs of each library dish, from Wikimedia Commons, shipped inside
// the app so a card shows its dish at once, offline, with nothing requested.
import type { ImageSourcePropType } from "react-native";

export type BundledPhoto = { source: ImageSourcePropType; credit: string | null };

export const BUNDLED_MEAL_PHOTOS: Record<string, BundledPhoto> = {};
