import { useEffect, useRef, useState } from "react";
import { Animated, Image, View } from "react-native";
import { MealImage } from "@/components/MealImage";
import { mealPhotoUrl, type Food, type Meal } from "@/kitchen";
import { useTheme } from "@/theme";

/**
 * A meal's picture. The plate drawn from the ingredients shows *immediately* and
 * is a complete picture in its own right — so there is no spinner and never a
 * "loading" state on screen. A real photo, generated by a free image service,
 * fades in quietly over the drawing if and when it arrives; if it never does
 * (offline, the service slow or down) the drawing simply stays. That is what
 * makes the card feel instant instead of "updating slowly": you always see a
 * finished plate the moment it renders.
 */

type Props = {
  meal: Meal;
  foods: Food[];
  haveIds: Set<string>;
  width: number;
  height: number;
};

/** Stop waiting on the photo after this — the drawing is the picture by then. */
const PHOTO_TIMEOUT_MS = 6000;

export function MealPhoto({ meal, foods, haveIds, width, height }: Props) {
  const { colors } = useTheme();
  const [loaded, setLoaded] = useState(false);
  const [giveUp, setGiveUp] = useState(false);
  const fade = useRef(new Animated.Value(0)).current;

  // Fetch close to the display size, not 1.4x: a smaller image generates and
  // arrives faster on the free service, and on a phone it still looks sharp.
  const uri = mealPhotoUrl(meal, { width: Math.round(width), height: Math.round(height) });

  useEffect(() => {
    setLoaded(false);
    setGiveUp(false);
    fade.setValue(0);
    const timer = setTimeout(() => setGiveUp(true), PHOTO_TIMEOUT_MS);
    return () => clearTimeout(timer);
  }, [uri, fade]);

  useEffect(() => {
    if (loaded) {
      Animated.timing(fade, { toValue: 1, duration: 400, useNativeDriver: true }).start();
    }
  }, [loaded, fade]);

  return (
    <View style={{ width, height, borderRadius: 18, overflow: "hidden", backgroundColor: colors.surfaceAlt }}>
      {/* the drawn plate — always there, instantly, as the base layer */}
      <MealImage foods={foods} haveIds={haveIds} width={width} height={height} />

      {/* the real photo fades in over it once it loads; nothing shows until then */}
      {!giveUp ? (
        <Animated.Image
          accessibilityIgnoresInvertColors
          source={{ uri }}
          resizeMode="cover"
          onLoad={() => setLoaded(true)}
          onError={() => setGiveUp(true)}
          style={{ position: "absolute", top: 0, left: 0, width, height, opacity: fade }}
        />
      ) : null}
    </View>
  );
}
